/* tslint:disable */
/* eslint-disable */
/**
 * os-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkUserOAuth2ProviderRequest
 */
export interface LinkUserOAuth2ProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof LinkUserOAuth2ProviderRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LinkUserOAuth2ProviderRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LinkUserOAuth2ProviderRequest
     */
    providerId: number;
}

/**
 * Check if a given object implements the LinkUserOAuth2ProviderRequest interface.
 */
export function instanceOfLinkUserOAuth2ProviderRequest(value: object): value is LinkUserOAuth2ProviderRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    return true;
}

export function LinkUserOAuth2ProviderRequestFromJSON(json: any): LinkUserOAuth2ProviderRequest {
    return LinkUserOAuth2ProviderRequestFromJSONTyped(json, false);
}

export function LinkUserOAuth2ProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkUserOAuth2ProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'providerId': json['provider_id'],
    };
}

export function LinkUserOAuth2ProviderRequestToJSON(json: any): LinkUserOAuth2ProviderRequest {
    return LinkUserOAuth2ProviderRequestToJSONTyped(json, false);
}

export function LinkUserOAuth2ProviderRequestToJSONTyped(value?: LinkUserOAuth2ProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'provider_id': value['providerId'],
    };
}

