[package]
name = "os-document-store"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Aicacia OS Document Store."
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-document-store"
rust-version = "1.91"

[dependencies]
os-api = { version = "0.1", path = "../api", default-features = false }
axum = { version = "0.8", default-features = false, features = ["ws"] }
build-time = { version = "0.1", default-features = false }
chrono = { version = "0.4", features = [
  "serde",
  "clock",
], default-features = false }
config = { version = "0.15", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false }
url = { version = "2.5", default-features = false }
tracing = { version = "0.1", features = ["std"], default-features = false }
log = { version = "0.4", default-features = false }
ciborium = { version = "0.2", default-features = false, features = ["std"] }
bytes = { version = "1.11", default-features = false, features = ["std"] }
serde_bytes = { version = "0.11", default-features = false, features = ["std"] }
hashbrown = { version = "0.16", default-features = false, features = [
  "serde",
  "default-hasher",
  "allocator-api2",
] }
utoipa = { version = "5.4", features = [
  "axum_extras",
  "chrono",
  "uuid",
  "macros",
], default-features = false }
utoipa-axum = { version = "0.2", default-features = false }
tokio = { version = "1.47", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "signal",
  "fs",
], default-features = false }
once_cell = { version = "1.19", default-features = false }
dashmap = { version = "6.1", default-features = false }
tower-http = { version = "0.6", features = [
  "cors",
  "trace",
  "compression-gzip",
], default-features = false }
http = { version = "1.3", default-features = false }
validator = { version = "0.20", features = [
  "derive",
], default-features = false }
jsonwebtoken = { version = "9", default-features = false }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10", default-features = false }
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
] }
sled = { version = "0.34", default-features = false }
automerge = { version = "0.7", default-features = false }
uuid = { version = "1.18", features = ["serde", "v3", "v7"] }

[lib]
name = "os_document_store"
