ARG BASE=os:local

FROM --platform=amd64 node:24-trixie-slim AS builder

RUN npm install -g pnpm@10

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm packages:build
RUN VITE_BASE_PATH=/oidc pnpm --filter os-oidc build
RUN VITE_BASE_PATH=/oidc-admin pnpm --filter os-oidc-admin build

FROM ${BASE}

WORKDIR /app

COPY --from=builder /app/apps/oidc/build /app/apps/oidc/build
COPY --from=builder /app/apps/oidc-admin/build /app/apps/oidc-admin/build
