/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
	AuthorizeRequest,
	BasicClaims,
	Client,
	ClientAllowed,
	ClientAuthorization,
	ClientAuthorizeRequest,
	ClientRegisterRequest,
	HttpError,
	JWKs,
	OpenIdConfiguration,
	ResponseMode,
	ResponseType,
	Token,
	UserInfo
} from '../models/index';
import {
	AuthorizeRequestFromJSON,
	AuthorizeRequestToJSON,
	BasicClaimsFromJSON,
	BasicClaimsToJSON,
	ClientFromJSON,
	ClientToJSON,
	ClientAllowedFromJSON,
	ClientAllowedToJSON,
	ClientAuthorizationFromJSON,
	ClientAuthorizationToJSON,
	ClientAuthorizeRequestFromJSON,
	ClientAuthorizeRequestToJSON,
	ClientRegisterRequestFromJSON,
	ClientRegisterRequestToJSON,
	HttpErrorFromJSON,
	HttpErrorToJSON,
	JWKsFromJSON,
	JWKsToJSON,
	OpenIdConfigurationFromJSON,
	OpenIdConfigurationToJSON,
	ResponseModeFromJSON,
	ResponseModeToJSON,
	ResponseTypeFromJSON,
	ResponseTypeToJSON,
	TokenFromJSON,
	TokenToJSON,
	UserInfoFromJSON,
	UserInfoToJSON
} from '../models/index';

export interface ApproveClientForUserRequest {
	clientId: string;
}

export interface AuthorizeRequest {
	clientId: string;
	responseType: ResponseType;
	responseMode: ResponseMode;
	scope: string;
	redirectUri: string;
	state?: string | null;
	nonce?: string | null;
	registration?: string | null;
	codeChallenge?: string | null;
	codeChallengeMethod?: string | null;
}

export interface AuthorizeClientRequest {
	clientAuthorizeRequest: ClientAuthorizeRequest;
}

export interface ClientRequest {
	clientId: string;
}

export interface EndSessionRequest {
	postLogoutRedirectUri: string;
	clientId?: string | null;
	idTokenHint?: string | null;
}

export interface IsClientAllowedForUserRequest {
	clientId: string;
	scope?: string;
}

export interface PostAuthorizeRequest {
	authorizeRequest: AuthorizeRequest;
}

export interface RegisterClientRequest {
	clientRegisterRequest: ClientRegisterRequest;
}

export interface RevokeRequest {
	token: string;
	clientAssertion?: string | null;
	clientAssertionType?: string | null;
	clientId?: string;
	clientSecret?: string | null;
	tokenTypeHint?: string | null;
}

export interface TokenRequest {
	clientAssertion?: string | null;
	clientAssertionType?: string | null;
	clientId?: string;
	clientSecret?: string | null;
	password?: string;
	scope?: string;
	username?: string;
	grantType?: TokenGrantTypeEnum;
	refreshToken?: string;
	code?: string;
	codeVerifier?: string | null;
}

/**
 * OidcApi - interface
 *
 * @export
 * @interface OidcApiInterface
 */
export interface OidcApiInterface {
	/**
	 *
	 * @param {string} clientId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	approveClientForUserRaw(
		requestParameters: ApproveClientForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	approveClientForUser(
		requestParameters: ApproveClientForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void>;

	/**
	 *
	 * @param {string} clientId
	 * @param {ResponseType} responseType
	 * @param {ResponseMode} responseMode
	 * @param {string} scope
	 * @param {string} redirectUri
	 * @param {string} [state]
	 * @param {string} [nonce]
	 * @param {string} [registration]
	 * @param {string} [codeChallenge]
	 * @param {string} [codeChallengeMethod]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	authorizeRaw(
		requestParameters: AuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	authorize(
		requestParameters: AuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void>;

	/**
	 *
	 * @param {ClientAuthorizeRequest} clientAuthorizeRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	authorizeClientRaw(
		requestParameters: AuthorizeClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<ClientAuthorization>>;

	/**
	 */
	authorizeClient(
		requestParameters: AuthorizeClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<ClientAuthorization>;

	/**
	 *
	 * @param {string} clientId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	clientRaw(
		requestParameters: ClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Client>>;

	/**
	 */
	client(
		requestParameters: ClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Client>;

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	deviceAuthorizeRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	deviceAuthorize(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

	/**
	 *
	 * @param {string} postLogoutRedirectUri
	 * @param {string} [clientId]
	 * @param {string} [idTokenHint]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	endSessionRaw(
		requestParameters: EndSessionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	endSession(
		requestParameters: EndSessionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void>;

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	introspectRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<BasicClaims>>;

	/**
	 */
	introspect(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicClaims>;

	/**
	 *
	 * @param {string} clientId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	isClientAllowedForUserRaw(
		requestParameters: IsClientAllowedForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<ClientAllowed>>;

	/**
	 */
	isClientAllowedForUser(
		requestParameters: IsClientAllowedForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<ClientAllowed>;

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	jwksRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<JWKs>>;

	/**
	 */
	jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JWKs>;

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	openidConfigurationRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<OpenIdConfiguration>>;

	/**
	 */
	openidConfiguration(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<OpenIdConfiguration>;

	/**
	 *
	 * @param {AuthorizeRequest} authorizeRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	postAuthorizeRaw(
		requestParameters: PostAuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	postAuthorize(
		requestParameters: PostAuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void>;

	/**
	 *
	 * @param {ClientRegisterRequest} clientRegisterRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	registerClientRaw(
		requestParameters: RegisterClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Client>>;

	/**
	 */
	registerClient(
		requestParameters: RegisterClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Client>;

	/**
	 *
	 * @param {string} token
	 * @param {string} [clientAssertion]
	 * @param {string} [clientAssertionType]
	 * @param {string} [clientId]
	 * @param {string} [clientSecret]
	 * @param {string} [tokenTypeHint]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	revokeRaw(
		requestParameters: RevokeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	revoke(
		requestParameters: RevokeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void>;

	/**
	 *
	 * @param {string} [clientAssertion]
	 * @param {string} [clientAssertionType]
	 * @param {string} [clientId]
	 * @param {string} [clientSecret]
	 * @param {string} [password]
	 * @param {string} [scope]
	 * @param {string} [username]
	 * @param {string} [grantType]
	 * @param {string} [refreshToken]
	 * @param {string} [code]
	 * @param {string} [codeVerifier]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	tokenRaw(
		requestParameters: TokenRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Token>>;

	/**
	 */
	token(
		requestParameters: TokenRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Token>;

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof OidcApiInterface
	 */
	userInfoRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserInfo>>;

	/**
	 */
	userInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfo>;
}

/**
 *
 */
export class OidcApi extends runtime.BaseAPI implements OidcApiInterface {
	/**
	 */
	async approveClientForUserRaw(
		requestParameters: ApproveClientForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['clientId'] == null) {
			throw new runtime.RequiredError(
				'clientId',
				'Required parameter "clientId" was null or undefined when calling approveClientForUser().'
			);
		}

		const queryParameters: any = {};

		if (requestParameters['clientId'] != null) {
			queryParameters['client_id'] = requestParameters['clientId'];
		}
		if (requestParameters['scope'] != null) {
			queryParameters['scope'] = requestParameters['scope'];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/approve-client`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async approveClientForUser(
		requestParameters: ApproveClientForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.approveClientForUserRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async authorizeRaw(
		requestParameters: AuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['clientId'] == null) {
			throw new runtime.RequiredError(
				'clientId',
				'Required parameter "clientId" was null or undefined when calling authorize().'
			);
		}

		if (requestParameters['responseType'] == null) {
			throw new runtime.RequiredError(
				'responseType',
				'Required parameter "responseType" was null or undefined when calling authorize().'
			);
		}

		if (requestParameters['responseMode'] == null) {
			throw new runtime.RequiredError(
				'responseMode',
				'Required parameter "responseMode" was null or undefined when calling authorize().'
			);
		}

		if (requestParameters['scope'] == null) {
			throw new runtime.RequiredError(
				'scope',
				'Required parameter "scope" was null or undefined when calling authorize().'
			);
		}

		if (requestParameters['redirectUri'] == null) {
			throw new runtime.RequiredError(
				'redirectUri',
				'Required parameter "redirectUri" was null or undefined when calling authorize().'
			);
		}

		const queryParameters: any = {};

		if (requestParameters['clientId'] != null) {
			queryParameters['client_id'] = requestParameters['clientId'];
		}

		if (requestParameters['responseType'] != null) {
			queryParameters['response_type'] = requestParameters['responseType'];
		}

		if (requestParameters['responseMode'] != null) {
			queryParameters['response_mode'] = requestParameters['responseMode'];
		}

		if (requestParameters['scope'] != null) {
			queryParameters['scope'] = requestParameters['scope'];
		}

		if (requestParameters['redirectUri'] != null) {
			queryParameters['redirect_uri'] = requestParameters['redirectUri'];
		}

		if (requestParameters['state'] != null) {
			queryParameters['state'] = requestParameters['state'];
		}

		if (requestParameters['nonce'] != null) {
			queryParameters['nonce'] = requestParameters['nonce'];
		}

		if (requestParameters['registration'] != null) {
			queryParameters['registration'] = requestParameters['registration'];
		}

		if (requestParameters['codeChallenge'] != null) {
			queryParameters['code_challenge'] = requestParameters['codeChallenge'];
		}

		if (requestParameters['codeChallengeMethod'] != null) {
			queryParameters['code_challenge_method'] = requestParameters['codeChallengeMethod'];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/oidc/api/authorize`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async authorize(
		requestParameters: AuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.authorizeRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async authorizeClientRaw(
		requestParameters: AuthorizeClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<ClientAuthorization>> {
		if (requestParameters['clientAuthorizeRequest'] == null) {
			throw new runtime.RequiredError(
				'clientAuthorizeRequest',
				'Required parameter "clientAuthorizeRequest" was null or undefined when calling authorizeClient().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/authorize-client`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: ClientAuthorizeRequestToJSON(requestParameters['clientAuthorizeRequest'])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ClientAuthorizationFromJSON(jsonValue)
		);
	}

	/**
	 */
	async authorizeClient(
		requestParameters: AuthorizeClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<ClientAuthorization> {
		const response = await this.authorizeClientRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async clientRaw(
		requestParameters: ClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Client>> {
		if (requestParameters['clientId'] == null) {
			throw new runtime.RequiredError(
				'clientId',
				'Required parameter "clientId" was null or undefined when calling client().'
			);
		}

		const queryParameters: any = {};

		if (requestParameters['clientId'] != null) {
			queryParameters['client_id'] = requestParameters['clientId'];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['client:read']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/client`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => ClientFromJSON(jsonValue));
	}

	/**
	 */
	async client(
		requestParameters: ClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Client> {
		const response = await this.clientRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async deviceAuthorizeRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/oidc/api/device-authorize`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async deviceAuthorize(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
		await this.deviceAuthorizeRaw(initOverrides);
	}

	/**
	 */
	async endSessionRaw(
		requestParameters: EndSessionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['postLogoutRedirectUri'] == null) {
			throw new runtime.RequiredError(
				'postLogoutRedirectUri',
				'Required parameter "postLogoutRedirectUri" was null or undefined when calling endSession().'
			);
		}

		const queryParameters: any = {};

		if (requestParameters['clientId'] != null) {
			queryParameters['client_id'] = requestParameters['clientId'];
		}

		if (requestParameters['idTokenHint'] != null) {
			queryParameters['id_token_hint'] = requestParameters['idTokenHint'];
		}

		if (requestParameters['postLogoutRedirectUri'] != null) {
			queryParameters['post_logout_redirect_uri'] = requestParameters['postLogoutRedirectUri'];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/oidc/api/end-session`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async endSession(
		requestParameters: EndSessionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.endSessionRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async introspectRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<BasicClaims>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/introspect`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => BasicClaimsFromJSON(jsonValue));
	}

	/**
	 */
	async introspect(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<BasicClaims> {
		const response = await this.introspectRaw(initOverrides);
		return await response.value();
	}

	/**
	 */
	async isClientAllowedForUserRaw(
		requestParameters: IsClientAllowedForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<ClientAllowed>> {
		if (requestParameters['clientId'] == null) {
			throw new runtime.RequiredError(
				'clientId',
				'Required parameter "clientId" was null or undefined when calling isClientAllowedForUser().'
			);
		}

		const queryParameters: any = {};

		if (requestParameters['clientId'] != null) {
			queryParameters['client_id'] = requestParameters['clientId'];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/client-allowed`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => ClientAllowedFromJSON(jsonValue));
	}

	/**
	 */
	async isClientAllowedForUser(
		requestParameters: IsClientAllowedForUserRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<ClientAllowed> {
		const response = await this.isClientAllowedForUserRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async jwksRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<JWKs>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/oidc/api/.well-known/jwks.json`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => JWKsFromJSON(jsonValue));
	}

	/**
	 */
	async jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JWKs> {
		const response = await this.jwksRaw(initOverrides);
		return await response.value();
	}

	/**
	 */
	async openidConfigurationRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<OpenIdConfiguration>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/oidc/api/.well-known/openid-configuration`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			OpenIdConfigurationFromJSON(jsonValue)
		);
	}

	/**
	 */
	async openidConfiguration(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<OpenIdConfiguration> {
		const response = await this.openidConfigurationRaw(initOverrides);
		return await response.value();
	}

	/**
	 */
	async postAuthorizeRaw(
		requestParameters: PostAuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['authorizeRequest'] == null) {
			throw new runtime.RequiredError(
				'authorizeRequest',
				'Required parameter "authorizeRequest" was null or undefined when calling postAuthorize().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		let urlPath = `/oidc/api/authorize`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: AuthorizeRequestToJSON(requestParameters['authorizeRequest'])
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async postAuthorize(
		requestParameters: PostAuthorizeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.postAuthorizeRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async registerClientRaw(
		requestParameters: RegisterClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Client>> {
		if (requestParameters['clientRegisterRequest'] == null) {
			throw new runtime.RequiredError(
				'clientRegisterRequest',
				'Required parameter "clientRegisterRequest" was null or undefined when calling registerClient().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['client:create']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/register-client`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: ClientRegisterRequestToJSON(requestParameters['clientRegisterRequest'])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => ClientFromJSON(jsonValue));
	}

	/**
	 */
	async registerClient(
		requestParameters: RegisterClientRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Client> {
		const response = await this.registerClientRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async revokeRaw(
		requestParameters: RevokeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['token'] == null) {
			throw new runtime.RequiredError(
				'token',
				'Required parameter "token" was null or undefined when calling revoke().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const consumes: runtime.Consume[] = [{ contentType: 'application/x-www-form-urlencoded' }];
		// @ts-ignore: canConsumeForm may be unused
		const canConsumeForm = runtime.canConsumeForm(consumes);

		let formParams: { append(param: string, value: any): any };
		let useForm = false;
		if (useForm) {
			formParams = new FormData();
		} else {
			formParams = new URLSearchParams();
		}

		if (requestParameters['clientAssertion'] != null) {
			formParams.append('client_assertion', requestParameters['clientAssertion'] as any);
		}

		if (requestParameters['clientAssertionType'] != null) {
			formParams.append('client_assertion_type', requestParameters['clientAssertionType'] as any);
		}

		if (requestParameters['clientId'] != null) {
			formParams.append('client_id', requestParameters['clientId'] as any);
		}

		if (requestParameters['clientSecret'] != null) {
			formParams.append('client_secret', requestParameters['clientSecret'] as any);
		}

		if (requestParameters['token'] != null) {
			formParams.append('token', requestParameters['token'] as any);
		}

		if (requestParameters['tokenTypeHint'] != null) {
			formParams.append('token_type_hint', requestParameters['tokenTypeHint'] as any);
		}

		let urlPath = `/oidc/api/revoke`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: formParams
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async revoke(
		requestParameters: RevokeRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.revokeRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async tokenRaw(
		requestParameters: TokenRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Token>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const consumes: runtime.Consume[] = [{ contentType: 'application/x-www-form-urlencoded' }];
		// @ts-ignore: canConsumeForm may be unused
		const canConsumeForm = runtime.canConsumeForm(consumes);

		let formParams: { append(param: string, value: any): any };
		let useForm = false;
		if (useForm) {
			formParams = new FormData();
		} else {
			formParams = new URLSearchParams();
		}

		if (requestParameters['clientAssertion'] != null) {
			formParams.append('client_assertion', requestParameters['clientAssertion'] as any);
		}

		if (requestParameters['clientAssertionType'] != null) {
			formParams.append('client_assertion_type', requestParameters['clientAssertionType'] as any);
		}

		if (requestParameters['clientId'] != null) {
			formParams.append('client_id', requestParameters['clientId'] as any);
		}

		if (requestParameters['clientSecret'] != null) {
			formParams.append('client_secret', requestParameters['clientSecret'] as any);
		}

		if (requestParameters['password'] != null) {
			formParams.append('password', requestParameters['password'] as any);
		}

		if (requestParameters['scope'] != null) {
			formParams.append('scope', requestParameters['scope'] as any);
		}

		if (requestParameters['username'] != null) {
			formParams.append('username', requestParameters['username'] as any);
		}

		if (requestParameters['grantType'] != null) {
			formParams.append('grant_type', requestParameters['grantType'] as any);
		}

		if (requestParameters['refreshToken'] != null) {
			formParams.append('refresh_token', requestParameters['refreshToken'] as any);
		}

		if (requestParameters['code'] != null) {
			formParams.append('code', requestParameters['code'] as any);
		}

		if (requestParameters['codeVerifier'] != null) {
			formParams.append('code_verifier', requestParameters['codeVerifier'] as any);
		}

		let urlPath = `/oidc/api/token`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: formParams
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
	}

	/**
	 */
	async token(
		requestParameters: TokenRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Token> {
		const response = await this.tokenRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async userInfoRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserInfo>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc/api/user-info`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoFromJSON(jsonValue));
	}

	/**
	 */
	async userInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfo> {
		const response = await this.userInfoRaw(initOverrides);
		return await response.value();
	}
}

/**
 * @export
 */
export const TokenGrantTypeEnum = {
	AuthorizationCode: 'authorization_code'
} as const;
export type TokenGrantTypeEnum = (typeof TokenGrantTypeEnum)[keyof typeof TokenGrantTypeEnum];
