DROP TABLE IF EXISTS "user_roles" CASCADE;
DROP TABLE IF EXISTS "roles_permissions" CASCADE;
DROP TABLE IF EXISTS "permissions" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;

DROP TABLE IF EXISTS "user_clients" CASCADE;
DROP TABLE IF EXISTS "user_oauth2_providers" CASCADE;
DROP TABLE IF EXISTS "user_passwords" CASCADE;
DROP TABLE IF EXISTS "user_phone_numbers" CASCADE;
DROP TABLE IF EXISTS "user_emails" CASCADE;
DROP TABLE IF EXISTS "user_infos" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "applications" CASCADE;
DROP TABLE IF EXISTS "oauth2_providers" CASCADE;
DROP TABLE IF EXISTS "clients" CASCADE;
DROP TABLE IF EXISTS "jwks" CASCADE;
DROP TABLE IF EXISTS "key_values" CASCADE;