//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "clients")]
pub struct Model {
  #[sea_orm(primary_key, unique)]
  pub id: i64,
  pub active: i64,
  pub name: String,
  #[sea_orm(unique)]
  pub client_id: String,
  pub client_secret: String,
  pub redirect_uris: Option<String>,
  pub post_logout_redirect_uris: Option<String>,
  pub logo_uri: Option<String>,
  pub client_uri: Option<String>,
  pub policy_uri: Option<String>,
  pub terms_of_service_uri: Option<String>,
  pub application_type: String,
  pub auth_method: String,
  pub grant_types: String,
  pub response_types: String,
  pub scopes: String,
  pub audience: Option<String>,
  pub access_token_expires_in_seconds: i64,
  pub id_token_expires_in_seconds: i64,
  pub refresh_expires_in_seconds: i64,
  pub updated_at: i64,
  pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::user_clients::Entity")]
  UserClients,
}

impl Related<super::user_clients::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserClients.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_clients::Relation::Users.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::user_clients::Relation::Clients.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
