//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub mod prelude;

pub mod applications;
pub mod clients;
pub mod jwks;
pub mod key_values;
pub mod o_auth2_providers;
pub mod permissions;
pub mod revoked_tokens;
pub mod roles;
pub mod roles_permissions;
pub mod user_clients;
pub mod user_emails;
pub mod user_infos;
pub mod user_o_auth2_providers;
pub mod user_passwords;
pub mod user_phone_numbers;
pub mod user_roles;
pub mod users;
