//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "o_auth2_providers")]
pub struct Model {
  #[sea_orm(primary_key, unique)]
  pub id: i64,
  #[sea_orm(default_value = "1")]
  pub active: i64,
  pub description: String,
  #[sea_orm(unique)]
  pub uri: String,
  pub client_id: String,
  pub client_secret: String,
  pub updated_at: i64,
  pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::user_o_auth2_providers::Entity")]
  UserOAuth2Providers,
}

impl Related<super::user_o_auth2_providers::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserOAuth2Providers.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_o_auth2_providers::Relation::Users.def()
  }
  fn via() -> Option<RelationDef> {
    Some(
      super::user_o_auth2_providers::Relation::OAuth2Providers
        .def()
        .rev(),
    )
  }
}

impl ActiveModelBehavior for ActiveModel {}
