//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
  #[sea_orm(primary_key, unique)]
  pub id: i64,
  pub active: i64,
  #[sea_orm(unique)]
  pub username: String,
  pub updated_at: i64,
  pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::user_clients::Entity")]
  UserClients,
  #[sea_orm(has_many = "super::user_emails::Entity")]
  UserEmails,
  #[sea_orm(has_one = "super::user_infos::Entity")]
  UserInfos,
  #[sea_orm(has_many = "super::user_o_auth2_providers::Entity")]
  UserOAuth2Providers,
  #[sea_orm(has_many = "super::user_passwords::Entity")]
  UserPasswords,
  #[sea_orm(has_many = "super::user_phone_numbers::Entity")]
  UserPhoneNumbers,
  #[sea_orm(has_many = "super::user_roles::Entity")]
  UserRoles,
}

impl Related<super::user_clients::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserClients.def()
  }
}

impl Related<super::user_emails::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserEmails.def()
  }
}

impl Related<super::user_infos::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserInfos.def()
  }
}

impl Related<super::user_o_auth2_providers::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserOAuth2Providers.def()
  }
}

impl Related<super::user_passwords::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserPasswords.def()
  }
}

impl Related<super::user_phone_numbers::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserPhoneNumbers.def()
  }
}

impl Related<super::user_roles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserRoles.def()
  }
}

impl Related<super::clients::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_clients::Relation::Clients.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::user_clients::Relation::Users.def().rev())
  }
}

impl Related<super::o_auth2_providers::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_o_auth2_providers::Relation::OAuth2Providers.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::user_o_auth2_providers::Relation::Users.def().rev())
  }
}

impl Related<super::roles::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_roles::Relation::Roles.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::user_roles::Relation::Users.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
