/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssignUserRoleRequest
 */
export interface AssignUserRoleRequest {
    /**
     * 
     * @type {number}
     * @memberof AssignUserRoleRequest
     */
    roleId: number;
}

/**
 * Check if a given object implements the AssignUserRoleRequest interface.
 */
export function instanceOfAssignUserRoleRequest(value: object): value is AssignUserRoleRequest {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function AssignUserRoleRequestFromJSON(json: any): AssignUserRoleRequest {
    return AssignUserRoleRequestFromJSONTyped(json, false);
}

export function AssignUserRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignUserRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
    };
}

export function AssignUserRoleRequestToJSON(json: any): AssignUserRoleRequest {
    return AssignUserRoleRequestToJSONTyped(json, false);
}

export function AssignUserRoleRequestToJSONTyped(value?: AssignUserRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role_id': value['roleId'],
    };
}

