/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorizationCode
 */
export interface AuthorizationCode {
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCode
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCode
     */
    type: AuthorizationCodeTypeEnum;
}


/**
 * @export
 */
export const AuthorizationCodeTypeEnum = {
    AuthorizationCode: 'authorization_code'
} as const;
export type AuthorizationCodeTypeEnum = typeof AuthorizationCodeTypeEnum[keyof typeof AuthorizationCodeTypeEnum];


/**
 * Check if a given object implements the AuthorizationCode interface.
 */
export function instanceOfAuthorizationCode(value: object): value is AuthorizationCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AuthorizationCodeFromJSON(json: any): AuthorizationCode {
    return AuthorizationCodeFromJSONTyped(json, false);
}

export function AuthorizationCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizationCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'type': json['type'],
    };
}

export function AuthorizationCodeToJSON(json: any): AuthorizationCode {
    return AuthorizationCodeToJSONTyped(json, false);
}

export function AuthorizationCodeToJSONTyped(value?: AuthorizationCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'type': value['type'],
    };
}

