/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthorizationCode } from './AuthorizationCode';
import {
    instanceOfAuthorizationCode,
    AuthorizationCodeFromJSON,
    AuthorizationCodeFromJSONTyped,
    AuthorizationCodeToJSON,
} from './AuthorizationCode';
import type { AuthorizationOneOf } from './AuthorizationOneOf';
import {
    instanceOfAuthorizationOneOf,
    AuthorizationOneOfFromJSON,
    AuthorizationOneOfFromJSONTyped,
    AuthorizationOneOfToJSON,
} from './AuthorizationOneOf';

/**
 * @type Authorization
 * 
 * @export
 */
export type Authorization = AuthorizationCode | AuthorizationOneOf;

export function AuthorizationFromJSON(json: any): Authorization {
    return AuthorizationFromJSONTyped(json, false);
}

export function AuthorizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Authorization {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAuthorizationCode(json)) {
        return AuthorizationCodeFromJSONTyped(json, true);
    }
    if (instanceOfAuthorizationOneOf(json)) {
        return AuthorizationOneOfFromJSONTyped(json, true);
    }
    return {} as any;
}

export function AuthorizationToJSON(json: any): any {
    return AuthorizationToJSONTyped(json, false);
}

export function AuthorizationToJSONTyped(value?: Authorization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAuthorizationCode(value)) {
        return AuthorizationCodeToJSON(value as AuthorizationCode);
    }
    if (instanceOfAuthorizationOneOf(value)) {
        return AuthorizationOneOfToJSON(value as AuthorizationOneOf);
    }
    return {};
}

