/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseType } from './ResponseType';
import {
    ResponseTypeFromJSON,
    ResponseTypeFromJSONTyped,
    ResponseTypeToJSON,
    ResponseTypeToJSONTyped,
} from './ResponseType';

/**
 * 
 * @export
 * @interface ClientAuthorizeRequest
 */
export interface ClientAuthorizeRequest {
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizeRequest
     */
    redirectUri: string;
    /**
     * 
     * @type {ResponseType}
     * @memberof ClientAuthorizeRequest
     */
    responseType: ResponseType;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizeRequest
     */
    scope: string;
}



/**
 * Check if a given object implements the ClientAuthorizeRequest interface.
 */
export function instanceOfClientAuthorizeRequest(value: object): value is ClientAuthorizeRequest {
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    if (!('responseType' in value) || value['responseType'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function ClientAuthorizeRequestFromJSON(json: any): ClientAuthorizeRequest {
    return ClientAuthorizeRequestFromJSONTyped(json, false);
}

export function ClientAuthorizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAuthorizeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUri': json['redirect_uri'],
        'responseType': ResponseTypeFromJSON(json['response_type']),
        'scope': json['scope'],
    };
}

export function ClientAuthorizeRequestToJSON(json: any): ClientAuthorizeRequest {
    return ClientAuthorizeRequestToJSONTyped(json, false);
}

export function ClientAuthorizeRequestToJSONTyped(value?: ClientAuthorizeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect_uri': value['redirectUri'],
        'response_type': ResponseTypeToJSON(value['responseType']),
        'scope': value['scope'],
    };
}

