/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientAuthorizationOneOf
 */
export interface ClientAuthorizationOneOf {
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    accessToken: string;
    /**
     * 
     * @type {number}
     * @memberof ClientAuthorizationOneOf
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    idToken?: string;
    /**
     * 
     * @type {Date}
     * @memberof ClientAuthorizationOneOf
     */
    issuedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    issuedTokenType: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    refreshToken?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientAuthorizationOneOf
     */
    refreshTokenExpiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    tokenType: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorizationOneOf
     */
    type: ClientAuthorizationOneOfTypeEnum;
}


/**
 * @export
 */
export const ClientAuthorizationOneOfTypeEnum = {
    AuthorizationCode: 'authorization_code'
} as const;
export type ClientAuthorizationOneOfTypeEnum = typeof ClientAuthorizationOneOfTypeEnum[keyof typeof ClientAuthorizationOneOfTypeEnum];


/**
 * Check if a given object implements the ClientAuthorizationOneOf interface.
 */
export function instanceOfClientAuthorizationOneOf(value: object): value is ClientAuthorizationOneOf {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('issuedAt' in value) || value['issuedAt'] === undefined) return false;
    if (!('issuedTokenType' in value) || value['issuedTokenType'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ClientAuthorizationOneOfFromJSON(json: any): ClientAuthorizationOneOf {
    return ClientAuthorizationOneOfFromJSONTyped(json, false);
}

export function ClientAuthorizationOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAuthorizationOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'idToken': json['id_token'] == null ? undefined : json['id_token'],
        'issuedAt': (new Date(json['issued_at'])),
        'issuedTokenType': json['issued_token_type'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'refreshTokenExpiresIn': json['refresh_token_expires_in'] == null ? undefined : json['refresh_token_expires_in'],
        'scope': json['scope'],
        'tokenType': json['token_type'],
        'type': json['type'],
    };
}

export function ClientAuthorizationOneOfToJSON(json: any): ClientAuthorizationOneOf {
    return ClientAuthorizationOneOfToJSONTyped(json, false);
}

export function ClientAuthorizationOneOfToJSONTyped(value?: ClientAuthorizationOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'id_token': value['idToken'],
        'issued_at': value['issuedAt'].toISOString(),
        'issued_token_type': value['issuedTokenType'],
        'refresh_token': value['refreshToken'],
        'refresh_token_expires_in': value['refreshTokenExpiresIn'],
        'scope': value['scope'],
        'token_type': value['tokenType'],
        'type': value['type'],
    };
}

