/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthorizationCode } from './AuthorizationCode';
import {
    instanceOfAuthorizationCode,
    AuthorizationCodeFromJSON,
    AuthorizationCodeFromJSONTyped,
    AuthorizationCodeToJSON,
} from './AuthorizationCode';
import type { ClientAuthorizationOneOf } from './ClientAuthorizationOneOf';
import {
    instanceOfClientAuthorizationOneOf,
    ClientAuthorizationOneOfFromJSON,
    ClientAuthorizationOneOfFromJSONTyped,
    ClientAuthorizationOneOfToJSON,
} from './ClientAuthorizationOneOf';

/**
 * @type ClientAuthorization
 * 
 * @export
 */
export type ClientAuthorization = AuthorizationCode | ClientAuthorizationOneOf;

export function ClientAuthorizationFromJSON(json: any): ClientAuthorization {
    return ClientAuthorizationFromJSONTyped(json, false);
}

export function ClientAuthorizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAuthorization {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAuthorizationCode(json)) {
        return AuthorizationCodeFromJSONTyped(json, true);
    }
    if (instanceOfClientAuthorizationOneOf(json)) {
        return ClientAuthorizationOneOfFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ClientAuthorizationToJSON(json: any): any {
    return ClientAuthorizationToJSONTyped(json, false);
}

export function ClientAuthorizationToJSONTyped(value?: ClientAuthorization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAuthorizationCode(value)) {
        return AuthorizationCodeToJSON(value as AuthorizationCode);
    }
    if (instanceOfClientAuthorizationOneOf(value)) {
        return ClientAuthorizationOneOfToJSON(value as ClientAuthorizationOneOf);
    }
    return {};
}

