/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserEmailRequest
 */
export interface CreateUserEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUserEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CreateUserEmailRequest interface.
 */
export function instanceOfCreateUserEmailRequest(value: object): value is CreateUserEmailRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateUserEmailRequestFromJSON(json: any): CreateUserEmailRequest {
    return CreateUserEmailRequestFromJSONTyped(json, false);
}

export function CreateUserEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function CreateUserEmailRequestToJSON(json: any): CreateUserEmailRequest {
    return CreateUserEmailRequestToJSONTyped(json, false);
}

export function CreateUserEmailRequestToJSONTyped(value?: CreateUserEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

