/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpErrorMessage } from './HttpErrorMessage';
import {
    HttpErrorMessageFromJSON,
    HttpErrorMessageFromJSONTyped,
    HttpErrorMessageToJSON,
    HttpErrorMessageToJSONTyped,
} from './HttpErrorMessage';

/**
 * 
 * @export
 * @interface HttpError
 */
export interface HttpError {
    /**
     * 
     * @type {{ [key: string]: Array<HttpErrorMessage>; }}
     * @memberof HttpError
     */
    messages: { [key: string]: Array<HttpErrorMessage>; };
    /**
     * 
     * @type {number}
     * @memberof HttpError
     */
    statusCode: number;
}

/**
 * Check if a given object implements the HttpError interface.
 */
export function instanceOfHttpError(value: object): value is HttpError {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function HttpErrorFromJSON(json: any): HttpError {
    return HttpErrorFromJSONTyped(json, false);
}

export function HttpErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpError {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'],
        'statusCode': json['status_code'],
    };
}

export function HttpErrorToJSON(json: any): HttpError {
    return HttpErrorToJSONTyped(json, false);
}

export function HttpErrorToJSONTyped(value?: HttpError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'],
        'status_code': value['statusCode'],
    };
}

