/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JWK } from './JWK';
import {
    JWKFromJSON,
    JWKFromJSONTyped,
    JWKToJSON,
    JWKToJSONTyped,
} from './JWK';

/**
 * 
 * @export
 * @interface JWKs
 */
export interface JWKs {
    /**
     * 
     * @type {Array<JWK>}
     * @memberof JWKs
     */
    keys: Array<JWK>;
}

/**
 * Check if a given object implements the JWKs interface.
 */
export function instanceOfJWKs(value: object): value is JWKs {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function JWKsFromJSON(json: any): JWKs {
    return JWKsFromJSONTyped(json, false);
}

export function JWKsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JWKs {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': ((json['keys'] as Array<any>).map(JWKFromJSON)),
    };
}

export function JWKsToJSON(json: any): JWKs {
    return JWKsToJSONTyped(json, false);
}

export function JWKsToJSONTyped(value?: JWKs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': ((value['keys'] as Array<any>).map(JWKToJSON)),
    };
}

