/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenIdConfiguration
 */
export interface OpenIdConfiguration {
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    authorizationEndpoint?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    claimsSupported: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    codeChallengeMethodsSupported: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    deviceAuthorizationEndpoint?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    grantTypesSupported: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    idTokenSigningAlgValuesSupported: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    issuer: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    jwksUri: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    responseModesSupported: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    responseTypesSupported: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    revocationEndpoint?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    scopesSupported: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    subjectTypesSupported: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    tokenEndpoint: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenIdConfiguration
     */
    tokenEndpointAuthMethodsSupported: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OpenIdConfiguration
     */
    userinfoEndpoint?: string | null;
}

/**
 * Check if a given object implements the OpenIdConfiguration interface.
 */
export function instanceOfOpenIdConfiguration(value: object): value is OpenIdConfiguration {
    if (!('claimsSupported' in value) || value['claimsSupported'] === undefined) return false;
    if (!('codeChallengeMethodsSupported' in value) || value['codeChallengeMethodsSupported'] === undefined) return false;
    if (!('grantTypesSupported' in value) || value['grantTypesSupported'] === undefined) return false;
    if (!('idTokenSigningAlgValuesSupported' in value) || value['idTokenSigningAlgValuesSupported'] === undefined) return false;
    if (!('issuer' in value) || value['issuer'] === undefined) return false;
    if (!('jwksUri' in value) || value['jwksUri'] === undefined) return false;
    if (!('responseModesSupported' in value) || value['responseModesSupported'] === undefined) return false;
    if (!('responseTypesSupported' in value) || value['responseTypesSupported'] === undefined) return false;
    if (!('scopesSupported' in value) || value['scopesSupported'] === undefined) return false;
    if (!('subjectTypesSupported' in value) || value['subjectTypesSupported'] === undefined) return false;
    if (!('tokenEndpoint' in value) || value['tokenEndpoint'] === undefined) return false;
    if (!('tokenEndpointAuthMethodsSupported' in value) || value['tokenEndpointAuthMethodsSupported'] === undefined) return false;
    return true;
}

export function OpenIdConfigurationFromJSON(json: any): OpenIdConfiguration {
    return OpenIdConfigurationFromJSONTyped(json, false);
}

export function OpenIdConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenIdConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationEndpoint': json['authorization_endpoint'] == null ? undefined : json['authorization_endpoint'],
        'claimsSupported': json['claims_supported'],
        'codeChallengeMethodsSupported': json['code_challenge_methods_supported'],
        'deviceAuthorizationEndpoint': json['device_authorization_endpoint'] == null ? undefined : json['device_authorization_endpoint'],
        'grantTypesSupported': json['grant_types_supported'],
        'idTokenSigningAlgValuesSupported': json['id_token_signing_alg_values_supported'],
        'issuer': json['issuer'],
        'jwksUri': json['jwks_uri'],
        'responseModesSupported': json['response_modes_supported'],
        'responseTypesSupported': json['response_types_supported'],
        'revocationEndpoint': json['revocation_endpoint'] == null ? undefined : json['revocation_endpoint'],
        'scopesSupported': json['scopes_supported'],
        'subjectTypesSupported': json['subject_types_supported'],
        'tokenEndpoint': json['token_endpoint'],
        'tokenEndpointAuthMethodsSupported': json['token_endpoint_auth_methods_supported'],
        'userinfoEndpoint': json['userinfo_endpoint'] == null ? undefined : json['userinfo_endpoint'],
    };
}

export function OpenIdConfigurationToJSON(json: any): OpenIdConfiguration {
    return OpenIdConfigurationToJSONTyped(json, false);
}

export function OpenIdConfigurationToJSONTyped(value?: OpenIdConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorization_endpoint': value['authorizationEndpoint'],
        'claims_supported': value['claimsSupported'],
        'code_challenge_methods_supported': value['codeChallengeMethodsSupported'],
        'device_authorization_endpoint': value['deviceAuthorizationEndpoint'],
        'grant_types_supported': value['grantTypesSupported'],
        'id_token_signing_alg_values_supported': value['idTokenSigningAlgValuesSupported'],
        'issuer': value['issuer'],
        'jwks_uri': value['jwksUri'],
        'response_modes_supported': value['responseModesSupported'],
        'response_types_supported': value['responseTypesSupported'],
        'revocation_endpoint': value['revocationEndpoint'],
        'scopes_supported': value['scopesSupported'],
        'subject_types_supported': value['subjectTypesSupported'],
        'token_endpoint': value['tokenEndpoint'],
        'token_endpoint_auth_methods_supported': value['tokenEndpointAuthMethodsSupported'],
        'userinfo_endpoint': value['userinfoEndpoint'],
    };
}

