/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserInfo
 */
export interface UpdateUserInfo {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfo
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateUserInfo interface.
 */
export function instanceOfUpdateUserInfo(value: object): value is UpdateUserInfo {
    return true;
}

export function UpdateUserInfoFromJSON(json: any): UpdateUserInfo {
    return UpdateUserInfoFromJSONTyped(json, false);
}

export function UpdateUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateUserInfoToJSON(json: any): UpdateUserInfo {
    return UpdateUserInfoToJSONTyped(json, false);
}

export function UpdateUserInfoToJSONTyped(value?: UpdateUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

