/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserEmailRequest
 */
export interface UpdateUserEmailRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserEmailRequest
     */
    isPrimary?: boolean | null;
}

/**
 * Check if a given object implements the UpdateUserEmailRequest interface.
 */
export function instanceOfUpdateUserEmailRequest(value: object): value is UpdateUserEmailRequest {
    return true;
}

export function UpdateUserEmailRequestFromJSON(json: any): UpdateUserEmailRequest {
    return UpdateUserEmailRequestFromJSONTyped(json, false);
}

export function UpdateUserEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
    };
}

export function UpdateUserEmailRequestToJSON(json: any): UpdateUserEmailRequest {
    return UpdateUserEmailRequestToJSONTyped(json, false);
}

export function UpdateUserEmailRequestToJSONTyped(value?: UpdateUserEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_primary': value['isPrimary'],
    };
}

