/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserPhoneNumberRequest
 */
export interface UpdateUserPhoneNumberRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserPhoneNumberRequest
     */
    isPrimary?: boolean | null;
}

/**
 * Check if a given object implements the UpdateUserPhoneNumberRequest interface.
 */
export function instanceOfUpdateUserPhoneNumberRequest(value: object): value is UpdateUserPhoneNumberRequest {
    return true;
}

export function UpdateUserPhoneNumberRequestFromJSON(json: any): UpdateUserPhoneNumberRequest {
    return UpdateUserPhoneNumberRequestFromJSONTyped(json, false);
}

export function UpdateUserPhoneNumberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPhoneNumberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
    };
}

export function UpdateUserPhoneNumberRequestToJSON(json: any): UpdateUserPhoneNumberRequest {
    return UpdateUserPhoneNumberRequestToJSONTyped(json, false);
}

export function UpdateUserPhoneNumberRequestToJSONTyped(value?: UpdateUserPhoneNumberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_primary': value['isPrimary'],
    };
}

