[package]
name = "os-signaling"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Aicacia OS Signaling Server."
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-os"
rust-version = "1.92"

[dependencies]
async-trait = { version = "0.1", default-features = false }
axum = { version = "0.8", features = [
  "tokio",
  "http1",
  "json",
  "form",
  "query",
  "macros",
  "ws",
], default-features = false }
build-time = { version = "0.1", default-features = false }
chrono = { version = "0.4", features = ["serde"], default-features = false }
config = { version = "0.15", features = ["json"], default-features = false }
dashmap = { version = "6.0", default-features = false }
futures-util = { version = "0.3", features = [
  "sink",
], default-features = false }
http = { version = "1.3", default-features = false }
jsonwebtoken = { version = "9.3", features = [
  "use_pem",
], default-features = false }
log = { version = "0.4", default-features = false }
os-api = { version = "0.1", path = "../api", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false }
tokio = { version = "1.48", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "signal",
], default-features = false }
tokio-util = { version = "0.7", features = ["io"], default-features = false }
redis = { version = "1.0", features = [
  "aio",
  "tokio-comp",
  "streams",
], default-features = false }
scopeguard = { version = "1.2", default-features = false }
tracing = { version = "0.1", features = ["std"], default-features = false }
url = { version = "2.5", default-features = false }
utoipa = { version = "5.4", features = [
  "axum_extras",
  "chrono",
  "uuid",
  "macros",
], default-features = false }
utoipa-axum = { version = "0.2", default-features = false }
uuid = { version = "1.18", features = ["serde", "v7", "std"] }

# bin dependencies
dotenvy = { version = "0.15", default-features = false, optional = true }
tracing-subscriber = { version = "0.3", features = [
  "ansi",
  "fmt",
  "std",
  "tracing-log",
  "env-filter",
], default-features = false, optional = true }
tracing-log = { version = "0.2", default-features = false, optional = true }
tower-http = { version = "0.6", features = [
  "cors",
  "trace",
  "compression-gzip",
], default-features = false, optional = true }
os-cli = { version = "0.1", path = "../cli", default-features = false, optional = true }
clap = { version = "4.5", features = [
  "std",
  "derive",
  "help",
], default-features = false, optional = true }
clap_complete = { version = "4.5", optional = true, default-features = false }

[dev-dependencies]
tokio = { version = "1.48", features = [
  "rt",
  "rt-multi-thread",
  "fs",
  "macros",
  "signal",
], default-features = false }
tracing-subscriber = "0.3"
dotenvy = "0.15"
tower = "0.5"
uuid = { version = "1.18", features = ["v4"] }

[lib]
name = "os_signaling"

[features]
completions = ["dep:clap_complete"]
bin = [
  "dep:clap",
  "dep:tracing-subscriber",
  "dep:tracing-log",
  "dep:dotenvy",
  "dep:os-cli",
  "dep:tower-http",
]
default = ["bin", "completions"]
