/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ClientAllowed
 */
export interface ClientAllowed {
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientAllowed
	 */
	allowedScopes: Array<string>;
}

/**
 * Check if a given object implements the ClientAllowed interface.
 */
export function instanceOfClientAllowed(value: object): value is ClientAllowed {
	if (!('allowedScopes' in value) || value['allowedScopes'] === undefined) return false;
	return true;
}

export function ClientAllowedFromJSON(json: any): ClientAllowed {
	return ClientAllowedFromJSONTyped(json, false);
}

export function ClientAllowedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAllowed {
	if (json == null) {
		return json;
	}
	return {
		allowedScopes: json['allowed_scopes']
	};
}

export function ClientAllowedToJSON(json: any): ClientAllowed {
	return ClientAllowedToJSONTyped(json, false);
}

export function ClientAllowedToJSONTyped(
	value?: ClientAllowed | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		allowed_scopes: value['allowedScopes']
	};
}
