/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ClientRegisterRequest
 */
export interface ClientRegisterRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ClientRegisterRequest
	 */
	accessTokenExpiresInSeconds: number;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	applicationType: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientRegisterRequest
	 */
	audience: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	authMethod: string;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	clientId: string;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	clientUri?: string | null;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientRegisterRequest
	 */
	grantTypes: Array<string>;
	/**
	 *
	 * @type {number}
	 * @memberof ClientRegisterRequest
	 */
	idTokenExpiresInSeconds: number;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	logoUri?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	policyUri?: string | null;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientRegisterRequest
	 */
	postLogoutRedirectUris?: Array<string> | null;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientRegisterRequest
	 */
	redirectUris?: Array<string> | null;
	/**
	 *
	 * @type {number}
	 * @memberof ClientRegisterRequest
	 */
	refreshExpiresInSeconds: number;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientRegisterRequest
	 */
	responseTypes: Array<string>;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ClientRegisterRequest
	 */
	scopes: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof ClientRegisterRequest
	 */
	termsOfServiceUri?: string | null;
}

/**
 * Check if a given object implements the ClientRegisterRequest interface.
 */
export function instanceOfClientRegisterRequest(value: object): value is ClientRegisterRequest {
	if (
		!('accessTokenExpiresInSeconds' in value) ||
		value['accessTokenExpiresInSeconds'] === undefined
	)
		return false;
	if (!('applicationType' in value) || value['applicationType'] === undefined) return false;
	if (!('audience' in value) || value['audience'] === undefined) return false;
	if (!('authMethod' in value) || value['authMethod'] === undefined) return false;
	if (!('clientId' in value) || value['clientId'] === undefined) return false;
	if (!('grantTypes' in value) || value['grantTypes'] === undefined) return false;
	if (!('idTokenExpiresInSeconds' in value) || value['idTokenExpiresInSeconds'] === undefined)
		return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	if (!('refreshExpiresInSeconds' in value) || value['refreshExpiresInSeconds'] === undefined)
		return false;
	if (!('responseTypes' in value) || value['responseTypes'] === undefined) return false;
	if (!('scopes' in value) || value['scopes'] === undefined) return false;
	return true;
}

export function ClientRegisterRequestFromJSON(json: any): ClientRegisterRequest {
	return ClientRegisterRequestFromJSONTyped(json, false);
}

export function ClientRegisterRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): ClientRegisterRequest {
	if (json == null) {
		return json;
	}
	return {
		accessTokenExpiresInSeconds: json['access_token_expires_in_seconds'],
		applicationType: json['application_type'],
		audience: json['audience'],
		authMethod: json['auth_method'],
		clientId: json['client_id'],
		clientUri: json['client_uri'] == null ? undefined : json['client_uri'],
		grantTypes: json['grant_types'],
		idTokenExpiresInSeconds: json['id_token_expires_in_seconds'],
		logoUri: json['logo_uri'] == null ? undefined : json['logo_uri'],
		name: json['name'],
		policyUri: json['policy_uri'] == null ? undefined : json['policy_uri'],
		postLogoutRedirectUris:
			json['post_logout_redirect_uris'] == null ? undefined : json['post_logout_redirect_uris'],
		redirectUris: json['redirect_uris'] == null ? undefined : json['redirect_uris'],
		refreshExpiresInSeconds: json['refresh_expires_in_seconds'],
		responseTypes: json['response_types'],
		scopes: json['scopes'],
		termsOfServiceUri:
			json['terms_of_service_uri'] == null ? undefined : json['terms_of_service_uri']
	};
}

export function ClientRegisterRequestToJSON(json: any): ClientRegisterRequest {
	return ClientRegisterRequestToJSONTyped(json, false);
}

export function ClientRegisterRequestToJSONTyped(
	value?: ClientRegisterRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		access_token_expires_in_seconds: value['accessTokenExpiresInSeconds'],
		application_type: value['applicationType'],
		audience: value['audience'],
		auth_method: value['authMethod'],
		client_id: value['clientId'],
		client_uri: value['clientUri'],
		grant_types: value['grantTypes'],
		id_token_expires_in_seconds: value['idTokenExpiresInSeconds'],
		logo_uri: value['logoUri'],
		name: value['name'],
		policy_uri: value['policyUri'],
		post_logout_redirect_uris: value['postLogoutRedirectUris'],
		redirect_uris: value['redirectUris'],
		refresh_expires_in_seconds: value['refreshExpiresInSeconds'],
		response_types: value['responseTypes'],
		scopes: value['scopes'],
		terms_of_service_uri: value['termsOfServiceUri']
	};
}
