/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Client
 */
export interface Client {
	/**
	 *
	 * @type {number}
	 * @memberof Client
	 */
	accessTokenExpiresInSeconds: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof Client
	 */
	active: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	applicationType: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Client
	 */
	audience: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	authMethod: string;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	clientId: string;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	clientSecret?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	clientUri?: string | null;
	/**
	 *
	 * @type {Date}
	 * @memberof Client
	 */
	createdAt: Date;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Client
	 */
	grantTypes: Array<string>;
	/**
	 *
	 * @type {number}
	 * @memberof Client
	 */
	id: number;
	/**
	 *
	 * @type {number}
	 * @memberof Client
	 */
	idTokenExpiresInSeconds: number;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	logoUri?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	policyUri?: string | null;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Client
	 */
	postLogoutRedirectUris?: Array<string> | null;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Client
	 */
	redirectUris?: Array<string> | null;
	/**
	 *
	 * @type {number}
	 * @memberof Client
	 */
	refreshExpiresInSeconds: number;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Client
	 */
	responseTypes: Array<string>;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Client
	 */
	scopes: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof Client
	 */
	termsOfServiceUri?: string | null;
	/**
	 *
	 * @type {Date}
	 * @memberof Client
	 */
	updatedAt: Date;
}

/**
 * Check if a given object implements the Client interface.
 */
export function instanceOfClient(value: object): value is Client {
	if (
		!('accessTokenExpiresInSeconds' in value) ||
		value['accessTokenExpiresInSeconds'] === undefined
	)
		return false;
	if (!('active' in value) || value['active'] === undefined) return false;
	if (!('applicationType' in value) || value['applicationType'] === undefined) return false;
	if (!('audience' in value) || value['audience'] === undefined) return false;
	if (!('authMethod' in value) || value['authMethod'] === undefined) return false;
	if (!('clientId' in value) || value['clientId'] === undefined) return false;
	if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
	if (!('grantTypes' in value) || value['grantTypes'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	if (!('idTokenExpiresInSeconds' in value) || value['idTokenExpiresInSeconds'] === undefined)
		return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	if (!('refreshExpiresInSeconds' in value) || value['refreshExpiresInSeconds'] === undefined)
		return false;
	if (!('responseTypes' in value) || value['responseTypes'] === undefined) return false;
	if (!('scopes' in value) || value['scopes'] === undefined) return false;
	if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
	return true;
}

export function ClientFromJSON(json: any): Client {
	return ClientFromJSONTyped(json, false);
}

export function ClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Client {
	if (json == null) {
		return json;
	}
	return {
		accessTokenExpiresInSeconds: json['access_token_expires_in_seconds'],
		active: json['active'],
		applicationType: json['application_type'],
		audience: json['audience'],
		authMethod: json['auth_method'],
		clientId: json['client_id'],
		clientSecret: json['client_secret'] == null ? undefined : json['client_secret'],
		clientUri: json['client_uri'] == null ? undefined : json['client_uri'],
		createdAt: new Date(json['created_at']),
		grantTypes: json['grant_types'],
		id: json['id'],
		idTokenExpiresInSeconds: json['id_token_expires_in_seconds'],
		logoUri: json['logo_uri'] == null ? undefined : json['logo_uri'],
		name: json['name'],
		policyUri: json['policy_uri'] == null ? undefined : json['policy_uri'],
		postLogoutRedirectUris:
			json['post_logout_redirect_uris'] == null ? undefined : json['post_logout_redirect_uris'],
		redirectUris: json['redirect_uris'] == null ? undefined : json['redirect_uris'],
		refreshExpiresInSeconds: json['refresh_expires_in_seconds'],
		responseTypes: json['response_types'],
		scopes: json['scopes'],
		termsOfServiceUri:
			json['terms_of_service_uri'] == null ? undefined : json['terms_of_service_uri'],
		updatedAt: new Date(json['updated_at'])
	};
}

export function ClientToJSON(json: any): Client {
	return ClientToJSONTyped(json, false);
}

export function ClientToJSONTyped(
	value?: Client | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		access_token_expires_in_seconds: value['accessTokenExpiresInSeconds'],
		active: value['active'],
		application_type: value['applicationType'],
		audience: value['audience'],
		auth_method: value['authMethod'],
		client_id: value['clientId'],
		client_secret: value['clientSecret'],
		client_uri: value['clientUri'],
		created_at: value['createdAt'].toISOString(),
		grant_types: value['grantTypes'],
		id: value['id'],
		id_token_expires_in_seconds: value['idTokenExpiresInSeconds'],
		logo_uri: value['logoUri'],
		name: value['name'],
		policy_uri: value['policyUri'],
		post_logout_redirect_uris: value['postLogoutRedirectUris'],
		redirect_uris: value['redirectUris'],
		refresh_expires_in_seconds: value['refreshExpiresInSeconds'],
		response_types: value['responseTypes'],
		scopes: value['scopes'],
		terms_of_service_uri: value['termsOfServiceUri'],
		updated_at: value['updatedAt'].toISOString()
	};
}
