/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface JWK
 */
export interface JWK {
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	alg: string;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	crv?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	e?: string | null;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof JWK
	 */
	keyOps?: Array<string> | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	kid: string;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	kty: string;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	n?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	use?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	x?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	x5c?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	x5t?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	x5tS256?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	x5u?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof JWK
	 */
	y?: string | null;
}

/**
 * Check if a given object implements the JWK interface.
 */
export function instanceOfJWK(value: object): value is JWK {
	if (!('alg' in value) || value['alg'] === undefined) return false;
	if (!('kid' in value) || value['kid'] === undefined) return false;
	if (!('kty' in value) || value['kty'] === undefined) return false;
	return true;
}

export function JWKFromJSON(json: any): JWK {
	return JWKFromJSONTyped(json, false);
}

export function JWKFromJSONTyped(json: any, ignoreDiscriminator: boolean): JWK {
	if (json == null) {
		return json;
	}
	return {
		alg: json['alg'],
		crv: json['crv'] == null ? undefined : json['crv'],
		e: json['e'] == null ? undefined : json['e'],
		keyOps: json['key_ops'] == null ? undefined : json['key_ops'],
		kid: json['kid'],
		kty: json['kty'],
		n: json['n'] == null ? undefined : json['n'],
		use: json['use'] == null ? undefined : json['use'],
		x: json['x'] == null ? undefined : json['x'],
		x5c: json['x5c'] == null ? undefined : json['x5c'],
		x5t: json['x5t'] == null ? undefined : json['x5t'],
		x5tS256: json['x5t_s256'] == null ? undefined : json['x5t_s256'],
		x5u: json['x5u'] == null ? undefined : json['x5u'],
		y: json['y'] == null ? undefined : json['y']
	};
}

export function JWKToJSON(json: any): JWK {
	return JWKToJSONTyped(json, false);
}

export function JWKToJSONTyped(value?: JWK | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		alg: value['alg'],
		crv: value['crv'],
		e: value['e'],
		key_ops: value['keyOps'],
		kid: value['kid'],
		kty: value['kty'],
		n: value['n'],
		use: value['use'],
		x: value['x'],
		x5c: value['x5c'],
		x5t: value['x5t'],
		x5t_s256: value['x5tS256'],
		x5u: value['x5u'],
		y: value['y']
	};
}
