/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OpenIdProfile
 */
export interface OpenIdProfile {
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	address?: string | null;
	/**
	 *
	 * @type {Date}
	 * @memberof OpenIdProfile
	 */
	birthdate?: Date | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	email?: string | null;
	/**
	 *
	 * @type {boolean}
	 * @memberof OpenIdProfile
	 */
	emailVerified?: boolean | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	familyName?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	gender?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	givenName?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	locale?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	middleName?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	name?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	nickname?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	phone?: string | null;
	/**
	 *
	 * @type {boolean}
	 * @memberof OpenIdProfile
	 */
	phoneVerified?: boolean | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	preferredUsername?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	profilePicture?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	website?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OpenIdProfile
	 */
	zoneInfo?: string | null;
}

/**
 * Check if a given object implements the OpenIdProfile interface.
 */
export function instanceOfOpenIdProfile(value: object): value is OpenIdProfile {
	return true;
}

export function OpenIdProfileFromJSON(json: any): OpenIdProfile {
	return OpenIdProfileFromJSONTyped(json, false);
}

export function OpenIdProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenIdProfile {
	if (json == null) {
		return json;
	}
	return {
		address: json['address'] == null ? undefined : json['address'],
		birthdate: json['birthdate'] == null ? undefined : new Date(json['birthdate']),
		email: json['email'] == null ? undefined : json['email'],
		emailVerified: json['email_verified'] == null ? undefined : json['email_verified'],
		familyName: json['family_name'] == null ? undefined : json['family_name'],
		gender: json['gender'] == null ? undefined : json['gender'],
		givenName: json['given_name'] == null ? undefined : json['given_name'],
		locale: json['locale'] == null ? undefined : json['locale'],
		middleName: json['middle_name'] == null ? undefined : json['middle_name'],
		name: json['name'] == null ? undefined : json['name'],
		nickname: json['nickname'] == null ? undefined : json['nickname'],
		phone: json['phone'] == null ? undefined : json['phone'],
		phoneVerified: json['phone_verified'] == null ? undefined : json['phone_verified'],
		preferredUsername: json['preferred_username'] == null ? undefined : json['preferred_username'],
		profilePicture: json['profile_picture'] == null ? undefined : json['profile_picture'],
		website: json['website'] == null ? undefined : json['website'],
		zoneInfo: json['zone_info'] == null ? undefined : json['zone_info']
	};
}

export function OpenIdProfileToJSON(json: any): OpenIdProfile {
	return OpenIdProfileToJSONTyped(json, false);
}

export function OpenIdProfileToJSONTyped(
	value?: OpenIdProfile | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		address: value['address'],
		birthdate: value['birthdate'] == null ? value['birthdate'] : value['birthdate'].toISOString(),
		email: value['email'],
		email_verified: value['emailVerified'],
		family_name: value['familyName'],
		gender: value['gender'],
		given_name: value['givenName'],
		locale: value['locale'],
		middle_name: value['middleName'],
		name: value['name'],
		nickname: value['nickname'],
		phone: value['phone'],
		phone_verified: value['phoneVerified'],
		preferred_username: value['preferredUsername'],
		profile_picture: value['profilePicture'],
		website: value['website'],
		zone_info: value['zoneInfo']
	};
}
