/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResponseMode = {
    Query: 'query',
    Fragment: 'fragment',
    FormPost: 'form_post',
    WebMessage: 'web_message'
} as const;
export type ResponseMode = typeof ResponseMode[keyof typeof ResponseMode];


export function instanceOfResponseMode(value: any): boolean {
    for (const key in ResponseMode) {
        if (Object.prototype.hasOwnProperty.call(ResponseMode, key)) {
            if (ResponseMode[key as keyof typeof ResponseMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseModeFromJSON(json: any): ResponseMode {
    return ResponseModeFromJSONTyped(json, false);
}

export function ResponseModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseMode {
    return json as ResponseMode;
}

export function ResponseModeToJSON(value?: ResponseMode | null): any {
    return value as any;
}

export function ResponseModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseMode {
    return value as ResponseMode;
}

