/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
	PermissionFromJSON,
	PermissionFromJSONTyped,
	PermissionToJSON,
	PermissionToJSONTyped
} from './Permission';

/**
 *
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	aud: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	client: string;
	/**
	 *
	 * @type {number}
	 * @memberof UserInfo
	 */
	exp: number;
	/**
	 *
	 * @type {number}
	 * @memberof UserInfo
	 */
	iat: number;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	iss: string;
	/**
	 *
	 * @type {number}
	 * @memberof UserInfo
	 */
	nbf: number;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	scope: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	sub: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	type: string;
	/**
	 *
	 * @type {number}
	 * @memberof UserInfo
	 */
	user: number;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	address?: string;
	/**
	 *
	 * @type {Date}
	 * @memberof UserInfo
	 */
	birthdate?: Date;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	email?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof UserInfo
	 */
	emailVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	familyName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	gender?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	givenName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	locale?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	middleName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	nickname?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	phone?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof UserInfo
	 */
	phoneVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	preferredUsername?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	profilePicture?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	website?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	zoneInfo?: string;
	/**
	 *
	 * @type {Array<Permission>}
	 * @memberof UserInfo
	 */
	permissions: Array<Permission>;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof UserInfo
	 */
	roles: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof UserInfo
	 */
	username: string;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
	if (!('aud' in value) || value['aud'] === undefined) return false;
	if (!('client' in value) || value['client'] === undefined) return false;
	if (!('exp' in value) || value['exp'] === undefined) return false;
	if (!('iat' in value) || value['iat'] === undefined) return false;
	if (!('iss' in value) || value['iss'] === undefined) return false;
	if (!('nbf' in value) || value['nbf'] === undefined) return false;
	if (!('scope' in value) || value['scope'] === undefined) return false;
	if (!('sub' in value) || value['sub'] === undefined) return false;
	if (!('type' in value) || value['type'] === undefined) return false;
	if (!('user' in value) || value['user'] === undefined) return false;
	if (!('permissions' in value) || value['permissions'] === undefined) return false;
	if (!('roles' in value) || value['roles'] === undefined) return false;
	if (!('username' in value) || value['username'] === undefined) return false;
	return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
	return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfo {
	if (json == null) {
		return json;
	}
	return {
		aud: json['aud'],
		client: json['client'],
		exp: json['exp'],
		iat: json['iat'],
		iss: json['iss'],
		nbf: json['nbf'],
		scope: json['scope'],
		sub: json['sub'],
		type: json['type'],
		user: json['user'],
		address: json['address'] == null ? undefined : json['address'],
		birthdate: json['birthdate'] == null ? undefined : new Date(json['birthdate']),
		email: json['email'] == null ? undefined : json['email'],
		emailVerified: json['email_verified'] == null ? undefined : json['email_verified'],
		familyName: json['family_name'] == null ? undefined : json['family_name'],
		gender: json['gender'] == null ? undefined : json['gender'],
		givenName: json['given_name'] == null ? undefined : json['given_name'],
		locale: json['locale'] == null ? undefined : json['locale'],
		middleName: json['middle_name'] == null ? undefined : json['middle_name'],
		name: json['name'] == null ? undefined : json['name'],
		nickname: json['nickname'] == null ? undefined : json['nickname'],
		phone: json['phone'] == null ? undefined : json['phone'],
		phoneVerified: json['phone_verified'] == null ? undefined : json['phone_verified'],
		preferredUsername: json['preferred_username'] == null ? undefined : json['preferred_username'],
		profilePicture: json['profile_picture'] == null ? undefined : json['profile_picture'],
		website: json['website'] == null ? undefined : json['website'],
		zoneInfo: json['zone_info'] == null ? undefined : json['zone_info'],
		permissions: (json['permissions'] as Array<any>).map(PermissionFromJSON),
		roles: json['roles'],
		username: json['username']
	};
}

export function UserInfoToJSON(json: any): UserInfo {
	return UserInfoToJSONTyped(json, false);
}

export function UserInfoToJSONTyped(
	value?: UserInfo | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		aud: value['aud'],
		client: value['client'],
		exp: value['exp'],
		iat: value['iat'],
		iss: value['iss'],
		nbf: value['nbf'],
		scope: value['scope'],
		sub: value['sub'],
		type: value['type'],
		user: value['user'],
		address: value['address'],
		birthdate: value['birthdate'] == null ? value['birthdate'] : value['birthdate'].toISOString(),
		email: value['email'],
		email_verified: value['emailVerified'],
		family_name: value['familyName'],
		gender: value['gender'],
		given_name: value['givenName'],
		locale: value['locale'],
		middle_name: value['middleName'],
		name: value['name'],
		nickname: value['nickname'],
		phone: value['phone'],
		phone_verified: value['phoneVerified'],
		preferred_username: value['preferredUsername'],
		profile_picture: value['profilePicture'],
		website: value['website'],
		zone_info: value['zoneInfo'],
		permissions: (value['permissions'] as Array<any>).map(PermissionToJSON),
		roles: value['roles'],
		username: value['username']
	};
}
