/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateUserPhoneNumberRequest,
  HttpError,
  UpdateUserPhoneNumberRequest,
  UserPhoneNumber,
} from '../models/index';
import {
    CreateUserPhoneNumberRequestFromJSON,
    CreateUserPhoneNumberRequestToJSON,
    HttpErrorFromJSON,
    HttpErrorToJSON,
    UpdateUserPhoneNumberRequestFromJSON,
    UpdateUserPhoneNumberRequestToJSON,
    UserPhoneNumberFromJSON,
    UserPhoneNumberToJSON,
} from '../models/index';

export interface CreateUserPhoneNumberHandlerRequest {
    userId: string;
    createUserPhoneNumberRequest: CreateUserPhoneNumberRequest;
}

export interface DeleteUserPhoneNumberHandlerRequest {
    userId: string;
    phoneId: string;
}

export interface GetUserPhoneNumberRequest {
    userId: string;
    phoneId: string;
}

export interface ListUserPhoneNumbersRequest {
    userId: string;
}

export interface UpdateUserPhoneNumberHandlerRequest {
    userId: string;
    phoneId: string;
    updateUserPhoneNumberRequest: UpdateUserPhoneNumberRequest;
}

export interface VerifyUserPhoneNumberHandlerRequest {
    userId: string;
    phoneId: string;
}

/**
 * UserPhoneNumberApi - interface
 * 
 * @export
 * @interface UserPhoneNumberApiInterface
 */
export interface UserPhoneNumberApiInterface {
    /**
     * 
     * @param {string} userId 
     * @param {CreateUserPhoneNumberRequest} createUserPhoneNumberRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPhoneNumberApiInterface
     */
    createUserPhoneNumberHandlerRaw(requestParameters: CreateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>>;

    /**
     */
    createUserPhoneNumberHandler(requestParameters: CreateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber>;

    /**
     * 
     * @param {string} userId 
     * @param {string} phoneId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPhoneNumberApiInterface
     */
    deleteUserPhoneNumberHandlerRaw(requestParameters: DeleteUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteUserPhoneNumberHandler(requestParameters: DeleteUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} userId 
     * @param {string} phoneId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPhoneNumberApiInterface
     */
    getUserPhoneNumberRaw(requestParameters: GetUserPhoneNumberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>>;

    /**
     */
    getUserPhoneNumber(requestParameters: GetUserPhoneNumberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber>;

    /**
     * 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPhoneNumberApiInterface
     */
    listUserPhoneNumbersRaw(requestParameters: ListUserPhoneNumbersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserPhoneNumber>>>;

    /**
     */
    listUserPhoneNumbers(requestParameters: ListUserPhoneNumbersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserPhoneNumber>>;

    /**
     * 
     * @param {string} userId 
     * @param {string} phoneId 
     * @param {UpdateUserPhoneNumberRequest} updateUserPhoneNumberRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPhoneNumberApiInterface
     */
    updateUserPhoneNumberHandlerRaw(requestParameters: UpdateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>>;

    /**
     */
    updateUserPhoneNumberHandler(requestParameters: UpdateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber>;

    /**
     * 
     * @param {string} userId 
     * @param {string} phoneId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPhoneNumberApiInterface
     */
    verifyUserPhoneNumberHandlerRaw(requestParameters: VerifyUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>>;

    /**
     */
    verifyUserPhoneNumberHandler(requestParameters: VerifyUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber>;

}

/**
 * 
 */
export class UserPhoneNumberApi extends runtime.BaseAPI implements UserPhoneNumberApiInterface {

    /**
     */
    async createUserPhoneNumberHandlerRaw(requestParameters: CreateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling createUserPhoneNumberHandler().'
            );
        }

        if (requestParameters['createUserPhoneNumberRequest'] == null) {
            throw new runtime.RequiredError(
                'createUserPhoneNumberRequest',
                'Required parameter "createUserPhoneNumberRequest" was null or undefined when calling createUserPhoneNumberHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/phone-numbers`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserPhoneNumberRequestToJSON(requestParameters['createUserPhoneNumberRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPhoneNumberFromJSON(jsonValue));
    }

    /**
     */
    async createUserPhoneNumberHandler(requestParameters: CreateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber> {
        const response = await this.createUserPhoneNumberHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteUserPhoneNumberHandlerRaw(requestParameters: DeleteUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserPhoneNumberHandler().'
            );
        }

        if (requestParameters['phoneId'] == null) {
            throw new runtime.RequiredError(
                'phoneId',
                'Required parameter "phoneId" was null or undefined when calling deleteUserPhoneNumberHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:delete"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/phone-numbers/{phone_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"phone_id"}}`, encodeURIComponent(String(requestParameters['phoneId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteUserPhoneNumberHandler(requestParameters: DeleteUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserPhoneNumberHandlerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getUserPhoneNumberRaw(requestParameters: GetUserPhoneNumberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserPhoneNumber().'
            );
        }

        if (requestParameters['phoneId'] == null) {
            throw new runtime.RequiredError(
                'phoneId',
                'Required parameter "phoneId" was null or undefined when calling getUserPhoneNumber().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/phone-numbers/{phone_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"phone_id"}}`, encodeURIComponent(String(requestParameters['phoneId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPhoneNumberFromJSON(jsonValue));
    }

    /**
     */
    async getUserPhoneNumber(requestParameters: GetUserPhoneNumberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber> {
        const response = await this.getUserPhoneNumberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listUserPhoneNumbersRaw(requestParameters: ListUserPhoneNumbersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserPhoneNumber>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserPhoneNumbers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/phone-numbers`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserPhoneNumberFromJSON));
    }

    /**
     */
    async listUserPhoneNumbers(requestParameters: ListUserPhoneNumbersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserPhoneNumber>> {
        const response = await this.listUserPhoneNumbersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateUserPhoneNumberHandlerRaw(requestParameters: UpdateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateUserPhoneNumberHandler().'
            );
        }

        if (requestParameters['phoneId'] == null) {
            throw new runtime.RequiredError(
                'phoneId',
                'Required parameter "phoneId" was null or undefined when calling updateUserPhoneNumberHandler().'
            );
        }

        if (requestParameters['updateUserPhoneNumberRequest'] == null) {
            throw new runtime.RequiredError(
                'updateUserPhoneNumberRequest',
                'Required parameter "updateUserPhoneNumberRequest" was null or undefined when calling updateUserPhoneNumberHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:update"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/phone-numbers/{phone_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"phone_id"}}`, encodeURIComponent(String(requestParameters['phoneId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserPhoneNumberRequestToJSON(requestParameters['updateUserPhoneNumberRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPhoneNumberFromJSON(jsonValue));
    }

    /**
     */
    async updateUserPhoneNumberHandler(requestParameters: UpdateUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber> {
        const response = await this.updateUserPhoneNumberHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async verifyUserPhoneNumberHandlerRaw(requestParameters: VerifyUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPhoneNumber>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling verifyUserPhoneNumberHandler().'
            );
        }

        if (requestParameters['phoneId'] == null) {
            throw new runtime.RequiredError(
                'phoneId',
                'Required parameter "phoneId" was null or undefined when calling verifyUserPhoneNumberHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:update"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/phone-numbers/{phone_id}/verify`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"phone_id"}}`, encodeURIComponent(String(requestParameters['phoneId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPhoneNumberFromJSON(jsonValue));
    }

    /**
     */
    async verifyUserPhoneNumberHandler(requestParameters: VerifyUserPhoneNumberHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPhoneNumber> {
        const response = await this.verifyUserPhoneNumberHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
