/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignUserRoleRequest,
  HttpError,
  UserPermissions,
  UserRole,
} from '../models/index';
import {
    AssignUserRoleRequestFromJSON,
    AssignUserRoleRequestToJSON,
    HttpErrorFromJSON,
    HttpErrorToJSON,
    UserPermissionsFromJSON,
    UserPermissionsToJSON,
    UserRoleFromJSON,
    UserRoleToJSON,
} from '../models/index';

export interface AssignUserRoleHandlerRequest {
    userId: string;
    assignUserRoleRequest: AssignUserRoleRequest;
}

export interface ListUserPermissionsRequest {
    userId: string;
}

export interface ListUserRolesRequest {
    userId: string;
}

export interface RemoveUserRoleHandlerRequest {
    userId: string;
    roleId: string;
}

/**
 * UserRoleApi - interface
 * 
 * @export
 * @interface UserRoleApiInterface
 */
export interface UserRoleApiInterface {
    /**
     * 
     * @param {string} userId 
     * @param {AssignUserRoleRequest} assignUserRoleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserRoleApiInterface
     */
    assignUserRoleHandlerRaw(requestParameters: AssignUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRole>>;

    /**
     */
    assignUserRoleHandler(requestParameters: AssignUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRole>;

    /**
     * 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserRoleApiInterface
     */
    listUserPermissionsRaw(requestParameters: ListUserPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPermissions>>;

    /**
     */
    listUserPermissions(requestParameters: ListUserPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPermissions>;

    /**
     * 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserRoleApiInterface
     */
    listUserRolesRaw(requestParameters: ListUserRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserRole>>>;

    /**
     */
    listUserRoles(requestParameters: ListUserRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserRole>>;

    /**
     * 
     * @param {string} userId 
     * @param {string} roleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserRoleApiInterface
     */
    removeUserRoleHandlerRaw(requestParameters: RemoveUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    removeUserRoleHandler(requestParameters: RemoveUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class UserRoleApi extends runtime.BaseAPI implements UserRoleApiInterface {

    /**
     */
    async assignUserRoleHandlerRaw(requestParameters: AssignUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRole>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling assignUserRoleHandler().'
            );
        }

        if (requestParameters['assignUserRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'assignUserRoleRequest',
                'Required parameter "assignUserRoleRequest" was null or undefined when calling assignUserRoleHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/roles`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignUserRoleRequestToJSON(requestParameters['assignUserRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRoleFromJSON(jsonValue));
    }

    /**
     */
    async assignUserRoleHandler(requestParameters: AssignUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRole> {
        const response = await this.assignUserRoleHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listUserPermissionsRaw(requestParameters: ListUserPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPermissions>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserPermissions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/permissions`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPermissionsFromJSON(jsonValue));
    }

    /**
     */
    async listUserPermissions(requestParameters: ListUserPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPermissions> {
        const response = await this.listUserPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listUserRolesRaw(requestParameters: ListUserRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserRole>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/roles`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserRoleFromJSON));
    }

    /**
     */
    async listUserRoles(requestParameters: ListUserRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserRole>> {
        const response = await this.listUserRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async removeUserRoleHandlerRaw(requestParameters: RemoveUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeUserRoleHandler().'
            );
        }

        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling removeUserRoleHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/oidc-admin/api/users/{user_id}/roles/{role_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"role_id"}}`, encodeURIComponent(String(requestParameters['roleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removeUserRoleHandler(requestParameters: RemoveUserRoleHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeUserRoleHandlerRaw(requestParameters, initOverrides);
    }

}
