/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
	CreateUserEmailRequest,
	HttpError,
	UpdateUserEmailRequest,
	UserEmail
} from '../models/index';
import {
	CreateUserEmailRequestFromJSON,
	CreateUserEmailRequestToJSON,
	HttpErrorFromJSON,
	HttpErrorToJSON,
	UpdateUserEmailRequestFromJSON,
	UpdateUserEmailRequestToJSON,
	UserEmailFromJSON,
	UserEmailToJSON
} from '../models/index';

export interface CreateUserEmailHandlerRequest {
	userId: string;
	createUserEmailRequest: CreateUserEmailRequest;
}

export interface DeleteUserEmailHandlerRequest {
	userId: string;
	emailId: string;
}

export interface GetUserEmailRequest {
	userId: string;
	emailId: string;
}

export interface ListUserEmailsRequest {
	userId: string;
}

export interface UpdateUserEmailHandlerRequest {
	userId: string;
	emailId: string;
	updateUserEmailRequest: UpdateUserEmailRequest;
}

export interface VerifyUserEmailHandlerRequest {
	userId: string;
	emailId: string;
}

/**
 * UserEmailApi - interface
 *
 * @export
 * @interface UserEmailApiInterface
 */
export interface UserEmailApiInterface {
	/**
	 *
	 * @param {string} userId
	 * @param {CreateUserEmailRequest} createUserEmailRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserEmailApiInterface
	 */
	createUserEmailHandlerRaw(
		requestParameters: CreateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>>;

	/**
	 */
	createUserEmailHandler(
		requestParameters: CreateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail>;

	/**
	 *
	 * @param {string} userId
	 * @param {string} emailId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserEmailApiInterface
	 */
	deleteUserEmailHandlerRaw(
		requestParameters: DeleteUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>>;

	/**
	 */
	deleteUserEmailHandler(
		requestParameters: DeleteUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void>;

	/**
	 *
	 * @param {string} userId
	 * @param {string} emailId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserEmailApiInterface
	 */
	getUserEmailRaw(
		requestParameters: GetUserEmailRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>>;

	/**
	 */
	getUserEmail(
		requestParameters: GetUserEmailRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail>;

	/**
	 *
	 * @param {string} userId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserEmailApiInterface
	 */
	listUserEmailsRaw(
		requestParameters: ListUserEmailsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Array<UserEmail>>>;

	/**
	 */
	listUserEmails(
		requestParameters: ListUserEmailsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Array<UserEmail>>;

	/**
	 *
	 * @param {string} userId
	 * @param {string} emailId
	 * @param {UpdateUserEmailRequest} updateUserEmailRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserEmailApiInterface
	 */
	updateUserEmailHandlerRaw(
		requestParameters: UpdateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>>;

	/**
	 */
	updateUserEmailHandler(
		requestParameters: UpdateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail>;

	/**
	 *
	 * @param {string} userId
	 * @param {string} emailId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserEmailApiInterface
	 */
	verifyUserEmailHandlerRaw(
		requestParameters: VerifyUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>>;

	/**
	 */
	verifyUserEmailHandler(
		requestParameters: VerifyUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail>;
}

/**
 *
 */
export class UserEmailApi extends runtime.BaseAPI implements UserEmailApiInterface {
	/**
	 */
	async createUserEmailHandlerRaw(
		requestParameters: CreateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>> {
		if (requestParameters['userId'] == null) {
			throw new runtime.RequiredError(
				'userId',
				'Required parameter "userId" was null or undefined when calling createUserEmailHandler().'
			);
		}

		if (requestParameters['createUserEmailRequest'] == null) {
			throw new runtime.RequiredError(
				'createUserEmailRequest',
				'Required parameter "createUserEmailRequest" was null or undefined when calling createUserEmailHandler().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['user:write']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc-admin/api/users/{user_id}/emails`;
		urlPath = urlPath.replace(
			`{${'user_id'}}`,
			encodeURIComponent(String(requestParameters['userId']))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: CreateUserEmailRequestToJSON(requestParameters['createUserEmailRequest'])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => UserEmailFromJSON(jsonValue));
	}

	/**
	 */
	async createUserEmailHandler(
		requestParameters: CreateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail> {
		const response = await this.createUserEmailHandlerRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async deleteUserEmailHandlerRaw(
		requestParameters: DeleteUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['userId'] == null) {
			throw new runtime.RequiredError(
				'userId',
				'Required parameter "userId" was null or undefined when calling deleteUserEmailHandler().'
			);
		}

		if (requestParameters['emailId'] == null) {
			throw new runtime.RequiredError(
				'emailId',
				'Required parameter "emailId" was null or undefined when calling deleteUserEmailHandler().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['user:write']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc-admin/api/users/{user_id}/emails/{email_id}`;
		urlPath = urlPath.replace(
			`{${'user_id'}}`,
			encodeURIComponent(String(requestParameters['userId']))
		);
		urlPath = urlPath.replace(
			`{${'email_id'}}`,
			encodeURIComponent(String(requestParameters['emailId']))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: 'DELETE',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async deleteUserEmailHandler(
		requestParameters: DeleteUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.deleteUserEmailHandlerRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async getUserEmailRaw(
		requestParameters: GetUserEmailRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>> {
		if (requestParameters['userId'] == null) {
			throw new runtime.RequiredError(
				'userId',
				'Required parameter "userId" was null or undefined when calling getUserEmail().'
			);
		}

		if (requestParameters['emailId'] == null) {
			throw new runtime.RequiredError(
				'emailId',
				'Required parameter "emailId" was null or undefined when calling getUserEmail().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['user:read']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc-admin/api/users/{user_id}/emails/{email_id}`;
		urlPath = urlPath.replace(
			`{${'user_id'}}`,
			encodeURIComponent(String(requestParameters['userId']))
		);
		urlPath = urlPath.replace(
			`{${'email_id'}}`,
			encodeURIComponent(String(requestParameters['emailId']))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => UserEmailFromJSON(jsonValue));
	}

	/**
	 */
	async getUserEmail(
		requestParameters: GetUserEmailRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail> {
		const response = await this.getUserEmailRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async listUserEmailsRaw(
		requestParameters: ListUserEmailsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Array<UserEmail>>> {
		if (requestParameters['userId'] == null) {
			throw new runtime.RequiredError(
				'userId',
				'Required parameter "userId" was null or undefined when calling listUserEmails().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['user:read']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc-admin/api/users/{user_id}/emails`;
		urlPath = urlPath.replace(
			`{${'user_id'}}`,
			encodeURIComponent(String(requestParameters['userId']))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserEmailFromJSON));
	}

	/**
	 */
	async listUserEmails(
		requestParameters: ListUserEmailsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Array<UserEmail>> {
		const response = await this.listUserEmailsRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async updateUserEmailHandlerRaw(
		requestParameters: UpdateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>> {
		if (requestParameters['userId'] == null) {
			throw new runtime.RequiredError(
				'userId',
				'Required parameter "userId" was null or undefined when calling updateUserEmailHandler().'
			);
		}

		if (requestParameters['emailId'] == null) {
			throw new runtime.RequiredError(
				'emailId',
				'Required parameter "emailId" was null or undefined when calling updateUserEmailHandler().'
			);
		}

		if (requestParameters['updateUserEmailRequest'] == null) {
			throw new runtime.RequiredError(
				'updateUserEmailRequest',
				'Required parameter "updateUserEmailRequest" was null or undefined when calling updateUserEmailHandler().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['user:write']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc-admin/api/users/{user_id}/emails/{email_id}`;
		urlPath = urlPath.replace(
			`{${'user_id'}}`,
			encodeURIComponent(String(requestParameters['userId']))
		);
		urlPath = urlPath.replace(
			`{${'email_id'}}`,
			encodeURIComponent(String(requestParameters['emailId']))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: 'PATCH',
				headers: headerParameters,
				query: queryParameters,
				body: UpdateUserEmailRequestToJSON(requestParameters['updateUserEmailRequest'])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => UserEmailFromJSON(jsonValue));
	}

	/**
	 */
	async updateUserEmailHandler(
		requestParameters: UpdateUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail> {
		const response = await this.updateUserEmailHandlerRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async verifyUserEmailHandlerRaw(
		requestParameters: VerifyUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<UserEmail>> {
		if (requestParameters['userId'] == null) {
			throw new runtime.RequiredError(
				'userId',
				'Required parameter "userId" was null or undefined when calling verifyUserEmailHandler().'
			);
		}

		if (requestParameters['emailId'] == null) {
			throw new runtime.RequiredError(
				'emailId',
				'Required parameter "emailId" was null or undefined when calling verifyUserEmailHandler().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('Authorization', ['user:write']);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/oidc-admin/api/users/{user_id}/emails/{email_id}/verify`;
		urlPath = urlPath.replace(
			`{${'user_id'}}`,
			encodeURIComponent(String(requestParameters['userId']))
		);
		urlPath = urlPath.replace(
			`{${'email_id'}}`,
			encodeURIComponent(String(requestParameters['emailId']))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => UserEmailFromJSON(jsonValue));
	}

	/**
	 */
	async verifyUserEmailHandler(
		requestParameters: VerifyUserEmailHandlerRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<UserEmail> {
		const response = await this.verifyUserEmailHandlerRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
