[package]
name = "os-model-migration"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Aicacia OS Model Migration."
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-os"
rust-version = "1.91"
publish = false

[lib]
name = "os_model_migration"
path = "src/lib.rs"

[dependencies]
log = { version = "0.4", default-features = false }
tokio = { version = "1.48", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "signal",
], default-features = false }
sea-orm-migration = { version = "2.0.0-rc.20", default-features = false, features = [
  "cli",
  "runtime-tokio-rustls",
  "sqlx-postgres",
  "sqlx-sqlite",
  "sqlx-mysql",
] }
