/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpError,
  JWK,
} from '../models/index';
import {
    HttpErrorFromJSON,
    HttpErrorToJSON,
    JWKFromJSON,
    JWKToJSON,
} from '../models/index';

export interface JwkByIdRequest {
    kid: number;
}

/**
 * JwkApi - interface
 * 
 * @export
 * @interface JwkApiInterface
 */
export interface JwkApiInterface {
    /**
     * 
     * @param {number} kid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JwkApiInterface
     */
    jwkByIdRaw(requestParameters: JwkByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JWK>>;

    /**
     */
    jwkById(requestParameters: JwkByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JWK>;

}

/**
 * 
 */
export class JwkApi extends runtime.BaseAPI implements JwkApiInterface {

    /**
     */
    async jwkByIdRaw(requestParameters: JwkByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JWK>> {
        if (requestParameters['kid'] == null) {
            throw new runtime.RequiredError(
                'kid',
                'Required parameter "kid" was null or undefined when calling jwkById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oidc/api/jwks/{kid}`;
        urlPath = urlPath.replace(`{${"kid"}}`, encodeURIComponent(String(requestParameters['kid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JWKFromJSON(jsonValue));
    }

    /**
     */
    async jwkById(requestParameters: JwkByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JWK> {
        const response = await this.jwkByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
