/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpError,
  JWKs,
  OpenIdConfiguration,
  ResponseMode,
  Token,
} from '../models/index';
import {
    HttpErrorFromJSON,
    HttpErrorToJSON,
    JWKsFromJSON,
    JWKsToJSON,
    OpenIdConfigurationFromJSON,
    OpenIdConfigurationToJSON,
    ResponseModeFromJSON,
    ResponseModeToJSON,
    TokenFromJSON,
    TokenToJSON,
} from '../models/index';

export interface AuthorizeRequest {
    clientId: string;
    redirectUri: string;
    responseMode: ResponseMode;
    responseType: string;
    scope: string;
    nonce?: string | null;
    state?: string | null;
}

export interface TokenRequest {
    clientId?: string | null;
    scope?: string | null;
    password?: string;
    username?: string;
    grantType?: TokenGrantTypeEnum;
    refreshToken?: string;
    code?: string;
}

/**
 * OidcApi - interface
 * 
 * @export
 * @interface OidcApiInterface
 */
export interface OidcApiInterface {
    /**
     * 
     * @param {string} clientId 
     * @param {string} redirectUri 
     * @param {ResponseMode} responseMode 
     * @param {string} responseType 
     * @param {string} scope 
     * @param {string} [nonce] 
     * @param {string} [state] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OidcApiInterface
     */
    authorizeRaw(requestParameters: AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authorize(requestParameters: AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OidcApiInterface
     */
    jwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JWKs>>;

    /**
     */
    jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JWKs>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OidcApiInterface
     */
    openidConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenIdConfiguration>>;

    /**
     */
    openidConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenIdConfiguration>;

    /**
     * 
     * @param {string} [clientId] 
     * @param {string} [scope] 
     * @param {string} [password] 
     * @param {string} [username] 
     * @param {string} [grantType] 
     * @param {string} [refreshToken] 
     * @param {string} [code] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OidcApiInterface
     */
    tokenRaw(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>>;

    /**
     */
    token(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token>;

}

/**
 * 
 */
export class OidcApi extends runtime.BaseAPI implements OidcApiInterface {

    /**
     */
    async authorizeRaw(requestParameters: AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling authorize().'
            );
        }

        if (requestParameters['redirectUri'] == null) {
            throw new runtime.RequiredError(
                'redirectUri',
                'Required parameter "redirectUri" was null or undefined when calling authorize().'
            );
        }

        if (requestParameters['responseMode'] == null) {
            throw new runtime.RequiredError(
                'responseMode',
                'Required parameter "responseMode" was null or undefined when calling authorize().'
            );
        }

        if (requestParameters['responseType'] == null) {
            throw new runtime.RequiredError(
                'responseType',
                'Required parameter "responseType" was null or undefined when calling authorize().'
            );
        }

        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling authorize().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['nonce'] != null) {
            formParams.append('nonce', requestParameters['nonce'] as any);
        }

        if (requestParameters['redirectUri'] != null) {
            formParams.append('redirect_uri', requestParameters['redirectUri'] as any);
        }

        if (requestParameters['responseMode'] != null) {
            formParams.append('response_mode', requestParameters['responseMode'] as any);
        }

        if (requestParameters['responseType'] != null) {
            formParams.append('response_type', requestParameters['responseType'] as any);
        }

        if (requestParameters['scope'] != null) {
            formParams.append('scope', requestParameters['scope'] as any);
        }

        if (requestParameters['state'] != null) {
            formParams.append('state', requestParameters['state'] as any);
        }


        let urlPath = `/oidc/api/authorize`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authorize(requestParameters: AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authorizeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async jwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JWKs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oidc/api/.well-known/jwks.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JWKsFromJSON(jsonValue));
    }

    /**
     */
    async jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JWKs> {
        const response = await this.jwksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async openidConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenIdConfiguration>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oidc/api/.well-known/openid-configuration`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenIdConfigurationFromJSON(jsonValue));
    }

    /**
     */
    async openidConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenIdConfiguration> {
        const response = await this.openidConfigurationRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async tokenRaw(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['scope'] != null) {
            formParams.append('scope', requestParameters['scope'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['refreshToken'] != null) {
            formParams.append('refresh_token', requestParameters['refreshToken'] as any);
        }

        if (requestParameters['code'] != null) {
            formParams.append('code', requestParameters['code'] as any);
        }


        let urlPath = `/oidc/api/token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     */
    async token(requestParameters: TokenRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.tokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const TokenGrantTypeEnum = {
    AuthorizationCode: 'authorization_code'
} as const;
export type TokenGrantTypeEnum = typeof TokenGrantTypeEnum[keyof typeof TokenGrantTypeEnum];
