[package]
name = "os-admin-ui"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Aicacia OS UI."
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-os"
rust-version = "1.92"
default-run = "os-admin-ui"

[dependencies]
axum = { version = "0.8", default-features = false, features = [
  "tokio",
  "http1",
  "json",
  "query",
  "macros",
] }
tokio = { version = "1.48", default-features = false, features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "signal",
] }
tokio-util = { version = "0.7", default-features = false, features = ["io"] }
axum-embed = { version = "0.1", default-features = false }
config = { version = "0.15", default-features = false, features = ["json"] }
rust-embed = { version = "8.9", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["std"] }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
os-api = { path = "../api", version = "0.1", default-features = false }

# bin dependencies
clap = { version = "4.5", default-features = false, features = [
  "std",
  "derive",
  "help",
], optional = true }
clap_complete = { version = "4.5", default-features = false, optional = true }
dotenvy = { version = "0.15", default-features = false, optional = true }
os-cli = { version = "0.1", path = "../cli", default-features = false, optional = true }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "ansi",
  "fmt",
  "std",
  "tracing-log",
  "env-filter",
], optional = true }
tracing-log = { version = "0.2", default-features = false, optional = true }

[features]
completions = ["dep:clap_complete"]
bin = [
  "dep:clap",
  "dep:tracing-subscriber",
  "dep:tracing-log",
  "dep:dotenvy",
  "dep:os-cli",
]
default = ["bin", "completions"]

[[bin]]
name = "os-admin-ui"

[lib]
name = "os_admin_ui"
