[package]
name = "os-db"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Aicacia OS Database."
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-os"
rust-version = "1.91"

[dependencies]
log = { version = "0.4", default-features = false }
sea-orm = { version = "2.0.0-rc.20", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }

[lib]
name = "os_db"
