[package]
name = "os-admin-ui-embed"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Aicacia OS UI."
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-os"
rust-version = "1.91"

[dependencies]
axum = { version = "0.8", default-features = false }
axum-embed = { version = "0.1", default-features = false }
config = { version = "0.15", default-features = false }
rust-embed = { version = "8.7", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }

[lib]
name = "os_admin_ui_embed"
