/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateUserPhoneNumberRequest
 */
export interface CreateUserPhoneNumberRequest {
	/**
	 *
	 * @type {string}
	 * @memberof CreateUserPhoneNumberRequest
	 */
	phoneNumber: string;
}

/**
 * Check if a given object implements the CreateUserPhoneNumberRequest interface.
 */
export function instanceOfCreateUserPhoneNumberRequest(
	value: object
): value is CreateUserPhoneNumberRequest {
	if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
	return true;
}

export function CreateUserPhoneNumberRequestFromJSON(json: any): CreateUserPhoneNumberRequest {
	return CreateUserPhoneNumberRequestFromJSONTyped(json, false);
}

export function CreateUserPhoneNumberRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): CreateUserPhoneNumberRequest {
	if (json == null) {
		return json;
	}
	return {
		phoneNumber: json['phone_number']
	};
}

export function CreateUserPhoneNumberRequestToJSON(json: any): CreateUserPhoneNumberRequest {
	return CreateUserPhoneNumberRequestToJSONTyped(json, false);
}

export function CreateUserPhoneNumberRequestToJSONTyped(
	value?: CreateUserPhoneNumberRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		phone_number: value['phoneNumber']
	};
}
