/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRole
 */
export interface UserRole {
    /**
     * 
     * @type {Date}
     * @memberof UserRole
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserRole
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof UserRole
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof UserRole
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserRole
     */
    uri: string;
}

/**
 * Check if a given object implements the UserRole interface.
 */
export function instanceOfUserRole(value: object): value is UserRole {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function UserRoleFromJSON(json: any): UserRole {
    return UserRoleFromJSONTyped(json, false);
}

export function UserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRole {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'],
        'id': json['id'],
        'updatedAt': (new Date(json['updated_at'])),
        'uri': json['uri'],
    };
}

export function UserRoleToJSON(json: any): UserRole {
    return UserRoleToJSONTyped(json, false);
}

export function UserRoleToJSONTyped(value?: UserRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'description': value['description'],
        'id': value['id'],
        'updated_at': value['updatedAt'].toISOString(),
        'uri': value['uri'],
    };
}

