/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRole
 */
export interface UserRole {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserRole
     */
    permissions: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserRole
     */
    uri: string;
}

/**
 * Check if a given object implements the UserRole interface.
 */
export function instanceOfUserRole(value: object): value is UserRole {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function UserRoleFromJSON(json: any): UserRole {
    return UserRoleFromJSONTyped(json, false);
}

export function UserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRole {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': json['permissions'],
        'uri': json['uri'],
    };
}

export function UserRoleToJSON(json: any): UserRole {
    return UserRoleToJSONTyped(json, false);
}

export function UserRoleToJSONTyped(value?: UserRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': value['permissions'],
        'uri': value['uri'],
    };
}

