/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOAuth2Provider
 */
export interface UserOAuth2Provider {
    /**
     * 
     * @type {Date}
     * @memberof UserOAuth2Provider
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserOAuth2Provider
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserOAuth2Provider
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserOAuth2Provider
     */
    oauth2ProviderId: string;
    /**
     * 
     * @type {Date}
     * @memberof UserOAuth2Provider
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserOAuth2Provider
     */
    uri: string;
    /**
     * 
     * @type {string}
     * @memberof UserOAuth2Provider
     */
    userId: string;
}

/**
 * Check if a given object implements the UserOAuth2Provider interface.
 */
export function instanceOfUserOAuth2Provider(value: object): value is UserOAuth2Provider {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('oauth2ProviderId' in value) || value['oauth2ProviderId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserOAuth2ProviderFromJSON(json: any): UserOAuth2Provider {
    return UserOAuth2ProviderFromJSONTyped(json, false);
}

export function UserOAuth2ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOAuth2Provider {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'email': json['email'],
        'name': json['name'],
        'oauth2ProviderId': json['oauth2_provider_id'],
        'updatedAt': (new Date(json['updated_at'])),
        'uri': json['uri'],
        'userId': json['user_id'],
    };
}

export function UserOAuth2ProviderToJSON(json: any): UserOAuth2Provider {
    return UserOAuth2ProviderToJSONTyped(json, false);
}

export function UserOAuth2ProviderToJSONTyped(value?: UserOAuth2Provider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'email': value['email'],
        'name': value['name'],
        'oauth2_provider_id': value['oauth2ProviderId'],
        'updated_at': value['updatedAt'].toISOString(),
        'uri': value['uri'],
        'user_id': value['userId'],
    };
}

