/* tslint:disable */
/* eslint-disable */
/**
 * os-admin
 * Aicacia OS Admin API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpError,
  LinkUserOAuth2ProviderRequest,
  UserOAuth2Provider,
} from '../models/index';
import {
    HttpErrorFromJSON,
    HttpErrorToJSON,
    LinkUserOAuth2ProviderRequestFromJSON,
    LinkUserOAuth2ProviderRequestToJSON,
    UserOAuth2ProviderFromJSON,
    UserOAuth2ProviderToJSON,
} from '../models/index';

export interface GetUserOauth2ProviderRequest {
    userId: string;
    providerId: string;
}

export interface LinkUserOauth2ProviderHandlerRequest {
    userId: string;
    linkUserOAuth2ProviderRequest: LinkUserOAuth2ProviderRequest;
}

export interface ListUserOauth2ProvidersRequest {
    userId: string;
}

export interface UnlinkUserOauth2ProviderHandlerRequest {
    userId: string;
    providerId: string;
}

/**
 * UserOauth2ProviderApi - interface
 * 
 * @export
 * @interface UserOauth2ProviderApiInterface
 */
export interface UserOauth2ProviderApiInterface {
    /**
     * 
     * @param {string} userId 
     * @param {string} providerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOauth2ProviderApiInterface
     */
    getUserOauth2ProviderRaw(requestParameters: GetUserOauth2ProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOAuth2Provider>>;

    /**
     */
    getUserOauth2Provider(requestParameters: GetUserOauth2ProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOAuth2Provider>;

    /**
     * 
     * @param {string} userId 
     * @param {LinkUserOAuth2ProviderRequest} linkUserOAuth2ProviderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOauth2ProviderApiInterface
     */
    linkUserOauth2ProviderHandlerRaw(requestParameters: LinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOAuth2Provider>>;

    /**
     */
    linkUserOauth2ProviderHandler(requestParameters: LinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOAuth2Provider>;

    /**
     * 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOauth2ProviderApiInterface
     */
    listUserOauth2ProvidersRaw(requestParameters: ListUserOauth2ProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserOAuth2Provider>>>;

    /**
     */
    listUserOauth2Providers(requestParameters: ListUserOauth2ProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserOAuth2Provider>>;

    /**
     * 
     * @param {string} userId 
     * @param {string} providerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOauth2ProviderApiInterface
     */
    unlinkUserOauth2ProviderHandlerRaw(requestParameters: UnlinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    unlinkUserOauth2ProviderHandler(requestParameters: UnlinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class UserOauth2ProviderApi extends runtime.BaseAPI implements UserOauth2ProviderApiInterface {

    /**
     */
    async getUserOauth2ProviderRaw(requestParameters: GetUserOauth2ProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOAuth2Provider>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserOauth2Provider().'
            );
        }

        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling getUserOauth2Provider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/api/users/{user_id}/oauth2-providers/{provider_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"provider_id"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserOAuth2ProviderFromJSON(jsonValue));
    }

    /**
     */
    async getUserOauth2Provider(requestParameters: GetUserOauth2ProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOAuth2Provider> {
        const response = await this.getUserOauth2ProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async linkUserOauth2ProviderHandlerRaw(requestParameters: LinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOAuth2Provider>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling linkUserOauth2ProviderHandler().'
            );
        }

        if (requestParameters['linkUserOAuth2ProviderRequest'] == null) {
            throw new runtime.RequiredError(
                'linkUserOAuth2ProviderRequest',
                'Required parameter "linkUserOAuth2ProviderRequest" was null or undefined when calling linkUserOauth2ProviderHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/api/users/{user_id}/oauth2-providers`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkUserOAuth2ProviderRequestToJSON(requestParameters['linkUserOAuth2ProviderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserOAuth2ProviderFromJSON(jsonValue));
    }

    /**
     */
    async linkUserOauth2ProviderHandler(requestParameters: LinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOAuth2Provider> {
        const response = await this.linkUserOauth2ProviderHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listUserOauth2ProvidersRaw(requestParameters: ListUserOauth2ProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserOAuth2Provider>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserOauth2Providers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/api/users/{user_id}/oauth2-providers`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserOAuth2ProviderFromJSON));
    }

    /**
     */
    async listUserOauth2Providers(requestParameters: ListUserOauth2ProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserOAuth2Provider>> {
        const response = await this.listUserOauth2ProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async unlinkUserOauth2ProviderHandlerRaw(requestParameters: UnlinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling unlinkUserOauth2ProviderHandler().'
            );
        }

        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling unlinkUserOauth2ProviderHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", ["user:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/api/users/{user_id}/oauth2-providers/{provider_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"provider_id"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async unlinkUserOauth2ProviderHandler(requestParameters: UnlinkUserOauth2ProviderHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unlinkUserOauth2ProviderHandlerRaw(requestParameters, initOverrides);
    }

}
