/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicClaims
 */
export interface BasicClaims {
    /**
     * 
     * @type {string}
     * @memberof BasicClaims
     */
    aud: string;
    /**
     * 
     * @type {number}
     * @memberof BasicClaims
     */
    exp: number;
    /**
     * 
     * @type {number}
     * @memberof BasicClaims
     */
    iat: number;
    /**
     * 
     * @type {string}
     * @memberof BasicClaims
     */
    iss: string;
    /**
     * 
     * @type {number}
     * @memberof BasicClaims
     */
    nbf: number;
    /**
     * 
     * @type {string}
     * @memberof BasicClaims
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof BasicClaims
     */
    sub: string;
    /**
     * 
     * @type {string}
     * @memberof BasicClaims
     */
    type: string;
}

/**
 * Check if a given object implements the BasicClaims interface.
 */
export function instanceOfBasicClaims(value: object): value is BasicClaims {
    if (!('aud' in value) || value['aud'] === undefined) return false;
    if (!('exp' in value) || value['exp'] === undefined) return false;
    if (!('iat' in value) || value['iat'] === undefined) return false;
    if (!('iss' in value) || value['iss'] === undefined) return false;
    if (!('nbf' in value) || value['nbf'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('sub' in value) || value['sub'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function BasicClaimsFromJSON(json: any): BasicClaims {
    return BasicClaimsFromJSONTyped(json, false);
}

export function BasicClaimsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicClaims {
    if (json == null) {
        return json;
    }
    return {
        
        'aud': json['aud'],
        'exp': json['exp'],
        'iat': json['iat'],
        'iss': json['iss'],
        'nbf': json['nbf'],
        'scope': json['scope'],
        'sub': json['sub'],
        'type': json['type'],
    };
}

export function BasicClaimsToJSON(json: any): BasicClaims {
    return BasicClaimsToJSONTyped(json, false);
}

export function BasicClaimsToJSONTyped(value?: BasicClaims | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aud': value['aud'],
        'exp': value['exp'],
        'iat': value['iat'],
        'iss': value['iss'],
        'nbf': value['nbf'],
        'scope': value['scope'],
        'sub': value['sub'],
        'type': value['type'],
    };
}

