/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientAuthorization
 */
export interface ClientAuthorization {
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorization
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAuthorization
     */
    type: ClientAuthorizationTypeEnum;
}


/**
 * @export
 */
export const ClientAuthorizationTypeEnum = {
    AuthorizationCode: 'authorization_code'
} as const;
export type ClientAuthorizationTypeEnum = typeof ClientAuthorizationTypeEnum[keyof typeof ClientAuthorizationTypeEnum];


/**
 * Check if a given object implements the ClientAuthorization interface.
 */
export function instanceOfClientAuthorization(value: object): value is ClientAuthorization {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ClientAuthorizationFromJSON(json: any): ClientAuthorization {
    return ClientAuthorizationFromJSONTyped(json, false);
}

export function ClientAuthorizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAuthorization {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'type': json['type'],
    };
}

export function ClientAuthorizationToJSON(json: any): ClientAuthorization {
    return ClientAuthorizationToJSONTyped(json, false);
}

export function ClientAuthorizationToJSONTyped(value?: ClientAuthorization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'type': value['type'],
    };
}

