/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpErrorMessage
 */
export interface HttpErrorMessage {
    /**
     * 
     * @type {string}
     * @memberof HttpErrorMessage
     */
    code: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof HttpErrorMessage
     */
    parameters: { [key: string]: any; };
}

/**
 * Check if a given object implements the HttpErrorMessage interface.
 */
export function instanceOfHttpErrorMessage(value: object): value is HttpErrorMessage {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function HttpErrorMessageFromJSON(json: any): HttpErrorMessage {
    return HttpErrorMessageFromJSONTyped(json, false);
}

export function HttpErrorMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpErrorMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'parameters': json['parameters'],
    };
}

export function HttpErrorMessageToJSON(json: any): HttpErrorMessage {
    return HttpErrorMessageToJSONTyped(json, false);
}

export function HttpErrorMessageToJSONTyped(value?: HttpErrorMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'parameters': value['parameters'],
    };
}

