/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS OIDC API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenIdClaims
 */
export interface OpenIdClaims {
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    aud: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    client: string;
    /**
     * 
     * @type {number}
     * @memberof OpenIdClaims
     */
    exp: number;
    /**
     * 
     * @type {number}
     * @memberof OpenIdClaims
     */
    iat: number;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    iss: string;
    /**
     * 
     * @type {number}
     * @memberof OpenIdClaims
     */
    nbf: number;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    sub: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    address?: string;
    /**
     * 
     * @type {Date}
     * @memberof OpenIdClaims
     */
    birthdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OpenIdClaims
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    phone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OpenIdClaims
     */
    phoneVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    preferredUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    profilePicture?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdClaims
     */
    zoneInfo?: string;
}

/**
 * Check if a given object implements the OpenIdClaims interface.
 */
export function instanceOfOpenIdClaims(value: object): value is OpenIdClaims {
    if (!('aud' in value) || value['aud'] === undefined) return false;
    if (!('client' in value) || value['client'] === undefined) return false;
    if (!('exp' in value) || value['exp'] === undefined) return false;
    if (!('iat' in value) || value['iat'] === undefined) return false;
    if (!('iss' in value) || value['iss'] === undefined) return false;
    if (!('nbf' in value) || value['nbf'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('sub' in value) || value['sub'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OpenIdClaimsFromJSON(json: any): OpenIdClaims {
    return OpenIdClaimsFromJSONTyped(json, false);
}

export function OpenIdClaimsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenIdClaims {
    if (json == null) {
        return json;
    }
    return {
        
        'aud': json['aud'],
        'client': json['client'],
        'exp': json['exp'],
        'iat': json['iat'],
        'iss': json['iss'],
        'nbf': json['nbf'],
        'scope': json['scope'],
        'sub': json['sub'],
        'type': json['type'],
        'address': json['address'] == null ? undefined : json['address'],
        'birthdate': json['birthdate'] == null ? undefined : (new Date(json['birthdate'])),
        'email': json['email'] == null ? undefined : json['email'],
        'emailVerified': json['email_verified'] == null ? undefined : json['email_verified'],
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'middleName': json['middle_name'] == null ? undefined : json['middle_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneVerified': json['phone_verified'] == null ? undefined : json['phone_verified'],
        'preferredUsername': json['preferred_username'] == null ? undefined : json['preferred_username'],
        'profilePicture': json['profile_picture'] == null ? undefined : json['profile_picture'],
        'website': json['website'] == null ? undefined : json['website'],
        'zoneInfo': json['zone_info'] == null ? undefined : json['zone_info'],
    };
}

export function OpenIdClaimsToJSON(json: any): OpenIdClaims {
    return OpenIdClaimsToJSONTyped(json, false);
}

export function OpenIdClaimsToJSONTyped(value?: OpenIdClaims | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aud': value['aud'],
        'client': value['client'],
        'exp': value['exp'],
        'iat': value['iat'],
        'iss': value['iss'],
        'nbf': value['nbf'],
        'scope': value['scope'],
        'sub': value['sub'],
        'type': value['type'],
        'address': value['address'],
        'birthdate': value['birthdate'] == null ? value['birthdate'] : value['birthdate'].toISOString(),
        'email': value['email'],
        'email_verified': value['emailVerified'],
        'family_name': value['familyName'],
        'gender': value['gender'],
        'given_name': value['givenName'],
        'locale': value['locale'],
        'middle_name': value['middleName'],
        'name': value['name'],
        'nickname': value['nickname'],
        'phone': value['phone'],
        'phone_verified': value['phoneVerified'],
        'preferred_username': value['preferredUsername'],
        'profile_picture': value['profilePicture'],
        'website': value['website'],
        'zone_info': value['zoneInfo'],
    };
}

