/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserPassword
 */
export interface UpdateUserPassword {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPassword
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPassword
     */
    passwordConfirmation: string;
}

/**
 * Check if a given object implements the UpdateUserPassword interface.
 */
export function instanceOfUpdateUserPassword(value: object): value is UpdateUserPassword {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passwordConfirmation' in value) || value['passwordConfirmation'] === undefined) return false;
    return true;
}

export function UpdateUserPasswordFromJSON(json: any): UpdateUserPassword {
    return UpdateUserPasswordFromJSONTyped(json, false);
}

export function UpdateUserPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'passwordConfirmation': json['password_confirmation'],
    };
}

export function UpdateUserPasswordToJSON(json: any): UpdateUserPassword {
    return UpdateUserPasswordToJSONTyped(json, false);
}

export function UpdateUserPasswordToJSONTyped(value?: UpdateUserPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'password_confirmation': value['passwordConfirmation'],
    };
}

