/* tslint:disable */
/* eslint-disable */
/**
 * os-oidc
 * Aicacia OS API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * 
 * @export
 * @interface UserPermissions
 */
export interface UserPermissions {
    /**
     * 
     * @type {Array<Permission>}
     * @memberof UserPermissions
     */
    permissions: Array<Permission>;
}

/**
 * Check if a given object implements the UserPermissions interface.
 */
export function instanceOfUserPermissions(value: object): value is UserPermissions {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function UserPermissionsFromJSON(json: any): UserPermissions {
    return UserPermissionsFromJSONTyped(json, false);
}

export function UserPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': ((json['permissions'] as Array<any>).map(PermissionFromJSON)),
    };
}

export function UserPermissionsToJSON(json: any): UserPermissions {
    return UserPermissionsToJSONTyped(json, false);
}

export function UserPermissionsToJSONTyped(value?: UserPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': ((value['permissions'] as Array<any>).map(PermissionToJSON)),
    };
}

